### ISSUE TITLE
FMC Arrivals Transitions

### ISSUE THREAD

**Issue by ValMar85** [saltysimulations/salty-747#101]
**Version of the mod**
0.2.0

**Describe the bug**
It's not possible to choose the correct transition in the arrivals page of the FMC, it's only possible to choose the top 4 transitions sorted alphabetically.

**To Reproduce**
1. Try an arrival to LFPG
2. Choose TINI9W as STAR
3. Choose ILS 27L as approach
4. Try to choose the OKIPA transition

**Expected behavior**
If there are many transitions, they should be listen in different pages as it happens for the STARs and approaches. 

**Screenshots**
![LFPG_arrivals](https://user-images.githubusercontent.com/74873095/99911729-a4990200-2cf6-11eb-94a4-ad119dd08724.png)

**Additional information**
The bug is also present in the default 747-8.

**Comment by valeriosouza** [comment]
related with #144

**Comment by 747-4EVER** [comment]
Fixed by #240.
