### ISSUE TITLE
[BUG] Low Fuel Consumption

### ISSUE THREAD

**Issue by dcherrie** [saltysimulations/salty-747#106]
**Version of the mod**
Latest development mod at time of post.

**Describe the bug**
The plane does not consume anywhere near the amount of fuel that it should be according to Simbrief.

**To Reproduce**
1. Use Simbrief for a flight using the 747-8 aircraft.
2. Over time, fuel burn isn't as realistic as what Simbrief predicts.

**Expected behavior**
Higher rate of fuel consumption closer to that of a Simbrief flight.

**Screenshots**
Have attached Simbrief with updated on-route fuel updates.
[YSSYKJFK_PDF_10Dec20.pdf](https://github.com/saltysimulations/salty-747/files/5676382/YSSYKJFK_PDF_10Dec20.pdf)

**References**
Currently flying from YSSY to KJFK which is a flight that a 747-8 shouldn't be able to make with a regular payload. After flying for about 13 hours now Simbrief says I should have about 93.6 thousand pounds of fuel, instead I have 241.4 thousand pounds left.

Currently with this fuel consumption, I think I'd be able to circumnavigate the globe on one tank of fuel.

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord: davidcherrie#1672

**Comment by Seabass17** [comment]
Still find in this to be the case running latest stable. 3 hours into a flight and burn is roughly 50% of SimBriefs predicted. Similar behaviour on a 9 hour flight yesterday. 

Todays flight SimBrief predicts 42.1 tonnes burnt, actual 21.1 burnt.

**Comment by dcherrie** [comment]
Just did my first flight in the 747 after the UK update and it seems fuel consumption is much more accurate. I'm flying from KBOS to EGKK and after halfway there, the predicted fuel burn in SimBrief is only 1700lbs off. I however am flying at max speed and not the ECON, and switch Thrust to CLB instead of CLB 1. Usually I'd only have burnt half the fuel I was expected to. Will keep update in further long haul flights.

**Comment by Seabass17** [comment]
Running latest dev and I'm still seeing about 50%-60% of expected fuel burn vs Simbrief. This is a stated cruise in the flight plan and 0.850 (again as stated in flight plan).

Current flight 4 hrs in, expected burn at waypoint 45.9 (kg) actual burn has been 26.5 (kg) This included a scheduled Step Climb form 350 to 370

**Comment by dcherrie** [comment]
After doing some long haul flights over the past couple of weeks, I’ve found that on average the fuel consumption is off from SimBrief by around 40-45%.

I had 2 flights that are included in the PDF that were below 40% however there was issues with those flights due to the excess weight the icing bug put on for the flight making the aircraft much heavier than it should be.

I would recommend increasing the fuel consumption burn by 35-40%. I’m willing to do this myself and test with flights but want to know what values exactly to edit to increase fuel burn in the flight model config.

[747-8 Fuel Consumption.pdf](https://github.com/saltysimulations/salty-747/files/6066867/747-8.Fuel.Consumption.pdf)

**Comment by 747-4EVER** [comment]
Fixed in dev.
