### ISSUE TITLE
747 8

### ISSUE THREAD

**Issue by JGPT60** [saltysimulations/salty-747#113]
Hi,
New to this so I apologize if i do anything wrong.
I Have tried to install 747 8 into msfs but how do i know if it was successful?
Does it have its own livery?
Thanks.
Joe T
JGPT60

**Comment by 747-4EVER** [comment]
There is no livery, but you can load up the 747 and see if you can move the IRS knobs. If you can then Salty is working correctly.

**Comment by ninjomcs** [comment]
If you need further help, go to the help channel in out Discord.

**Comment by JGPT60** [comment]
Thanks guys,
Working great .
JT

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by JGPT60** [comment]
Hi,
Until it ctd’d.
Thanks

JT
________________________________

**Comment by ninjomcs** [comment]
Please use the help channel in our Discord for support. GitHub issues are only used for requests or bugs.
