### ISSUE TITLE
[BUG] FMC Blank

### ISSUE THREAD

**Issue by sahajshah21** [saltysimulations/salty-747#121]
**2.1**
Stable

FMC shows up blank no matter what. Even after alignment

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
Update or uninstall your A32NX.
