### ISSUE TITLE
[REQUEST] ABILITY TO PUT IN COORDINATES AS WAYPOINTS INTO THE FMC

### ISSUE THREAD

**Issue by Phuqq** [saltysimulations/salty-747#122]
### ISSUE
I don't know if it is a general problem with the MSFS, but when I wanted to do a flight from Vancouver to Frankfurt I came across the problem of not being able to enter coordinates into the FMC. I tried multiple conversions of the coordinates but none of them seem to work and end up with a "NOT IN DATABASE" message. However, the ability to have the plane overfly coordinates is there, since a flightplan created in the NavLog page of the FS will already enter coordinates to the FMC into the waypointlist.

It would be really nice to see the function of adding coordinates as waypoints, since not being able to properly enter a route is really frustrating and, in my opinion gamebreaking as well. The only way to do the flight I wanted with a not pre-planned route from the FS, is to fly via Russia and use existing waypoints.

### EXPECTED BEHAVIOR
The standard format for entering coordinates into the FMC is: Ex. for the coordinate: 053N090W you would enter 53N90 or 53N090W into the FMC.

For any inquieries or questions feel free to contact me via discord [PZK] phuqq_#2549

Kindest regards.

**Comment by valenzz2004** [comment]
To answer your question in terms of north atlantic waypoints or oceanic waypoints the waypoint would be spelt for instance your example coordinate would be spelt 5390N where the first 2 digits is the longitudinal waypoint (north or south) and the 3rd and 4th digits are a lattitudinal waypoint (east or west) and then it is followed by an S or an N to indicate northern or southern Hemosphere

**Comment by Phuqq** [comment]
Yes, I know. It's also dependent on the aircraft. But you're right. I'll try to enter it that way in a minute, but I'm pretty sure I tried this one too and it didn't work.

**Comment by valenzz2004** [comment]
do you have a flight plan so i can try figure it out

**Comment by Phuqq** [comment]
Sure. 
This is the flightplan from yesterday: https://www.simbrief.com/ofp/flightplans/CYVREDDF_PDF_1609168316.pdf
And this is the route seperatly: DCT 53N110W/N0495F350 55N100W 56N090W 58N080W 58N070W DCT LAKES/M086F370 DCT URTAK DCT 59N050W 58N040W 57N030W 55N020W DCT DOGAL/N0493F370 DCT BEXET/N0491F390 DCT BAKUR N546 STU UL9 KONAN UL607 SPI T180 NIVNU T847 TUTOV DCT RAMOB DCT

**Comment by valenzz2004** [comment]
no worries give me ten and ill see what i can do

**Comment by valenzz2004** [comment]
can you confirm your discord i cant find it lets talk there as its more appropriate

**Comment by valenzz2004** [comment]
i added you on discord
