### ISSUE TITLE
[BUG] Flap Speeds Display Incorrect

### ISSUE THREAD

**Issue by LaneTOGA** [saltysimulations/salty-747#123]
**Version of the mod**

**Describe the bug**

**To Reproduce**
1. Set PREF INIT
2. Fly aircraft
3. You will not speed for current flaps shown, not other flap speeds

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
i'm unsure what you mean sorry, if you could create a new issue filling in all of the points that would be great

**Comment by LaneTOGA** [comment]
Hi NinJo

On the PFD (Primary Flight Display, Captain's left screen) the flap speed is only show for one flap setting (example, Flaps 5).
In reality, up to 20,000' the PFD displays:

- On Take Off: V1 and VR
- On Landing: VREF
- Also when maneuvering for flap retraction/extension: speed for current flap setting AND next lesser flap setting.
