### ISSUE TITLE
[BUG] Navigation Display & VSI Are Blank After Starting Up from Cold & Dark

### ISSUE THREAD

**Issue by miejoe** [saltysimulations/salty-747#124]
**Version of the mod**
v0.2.1 (Main Stable Release)

**Describe the bug**
After starting from cold & dark at gate or ramp rather than on runway with engines running, the Navigation Display is mostly blank and completely not functional for the entire flight. The Vertical Speed Indicator on the Primary Flight Display is also missing.

**To Reproduce**
1. Start from a gate or parking.
2. Follow the startup procedures, either manually using checklist or AI pilot.
3. For duration of flight, Navigation Display is mostly blank, PFD is missing Vertical Speed.

**Expected behavior**

**Screenshots**
![Blank Nav Display](https://user-images.githubusercontent.com/76739276/103292872-5a213a00-49b4-11eb-86c6-d265db3c2f05.png)

**References**

**Additional information**
Works fine in original 747-8i. The issue seems to be introduced by the mod?

**Comment by ninjomcs** [comment]
This is not a bug, but intended behavior (like it is in the real 748) and one of the features of the mod. You have to align the IRS by turning the 3 IRS knobs on the overhead to NAV. Alignment will take up to 10 minutes. Use the help channel in Discord if you still need help.

**Comment by miejoe** [comment]
Ok, thanks for the help ninjomcs!
