### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fredsflying** [saltysimulations/salty-747#125]
**Version of the mod**

**Describe the bug**

**To Reproduce**
1. Downloaded and dropped into community file
2. Then open up the game as usual and load the 747 and straight away the fms screen does not dispkay
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
Update or uninstall your A32NX.
