### ISSUE TITLE
[BUG] VNAV with latest jupdate 1.12.13.0,  Slow climb and cruise speeds,  245 knots max.

### ISSUE THREAD

**Issue by rvlasek** [saltysimulations/salty-747#126]
**Version of the mod**
Using Dev version

**Describe the bug**
BUG] VNAV with latest jupdate 1.12.13.0,  Slow climb and cruise speeds,  245 knots max.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
Faster and more accourate speeds for climb and cruise, decent,  seems to be fine on previous versions of MSFS 2020

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?Only happens on this mod 747

Your Discord:

**Comment by c7nb4e** [comment]
I observed this behaviour on the default 747-8 also. After takeoff, I switch the autopilot on (LNAV and VNAV), aircraft accelerates to about 250 knots up to FL 100, above that further accelerates but all of a sudden decelerates again to the mentioned 245 knots max.

Greetz, Chris

**Comment by tabasc** [comment]
Experiencing this also. Other than this everything running smoothly, big thanks to all involved in making the 747 fixes, night and day from what it used to be.
