### ISSUE TITLE
[BUG] FD and FCU won't turn on

### ISSUE THREAD

**Issue by Cspielman63** [saltysimulations/salty-747#141]
**Version of the mod**
 
Dev
**Describe the bug**

The Flight Director and FCU doesn't work when I attempt to turn it on.
**To Reproduce**
1. Load in C&D in 747
2. Try to turn on flight director and use FCU
3. 
4. 

**Expected behavior**

FD to turn on and See the FCU numbers
**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
Unable to reproduce, not enough information provided.
