### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by airifr** [saltysimulations/salty-747#143]
**Version of the mod**

dev

**Describe the bug**

When checking on the EFIS panel the different ND modes, APP VOR MAP PLN, going from MAP to PLN, the sim froze, and no mouse or flight controls nor pressing ESC effective, still hear sim sound in background but that's it. Nothing clickable in the flight deck. No mouse cursor nor hand when hovering on the buttons/switches/knobs. Mouse pointer stuck to knob display. Switch position stayed on MAP instead of going to PLN. Please see video.

https://yadi.sk/i/dfoOvEc9w0LVgg

**To Reproduce**
1. switch EFIS knob from MAP to VOR to MAP to PLN..
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
unable to reproduce, likely a one-time local issue
