### ISSUE TITLE
[REQUEST] Correct autothrottle behaviour during manual landing

### ISSUE THREAD

**Issue by tariq-a** [saltysimulations/salty-747#145]
**Is your feature request related to a problem? If so, please describe.**

The autothrottle does not behave correctly during a manual landing.
After disconnecting the autopilot (but leaving the autothrottle on) the PFD and behaviour is correct until ~20 feet AGL. 
At ~20 feet AGL, the APP switch deactivates incorrectly and the PFD displays IDLE + LNAV.
Despite displaying IDLE, the autothrottle does not reduce thrust, requiring that it is disarmed manually.

**Describe the feature you want implemented.**

According to the FCOM (on page 866):

> When autothrottle is used during manual landing, thrust reduces to IDLE at 25 feet
radio altitude when the pitch mode is VNAV SPD, VNAV PTH, V/S, or G/S. The
autothrottle does not retard if pitch mode is TO/GA or FLCH.

**References**

Here is a video I found of an autothrottle landing of a 747-8F:
https://www.youtube.com/watch?v=4LU7zTfTcAc&ab_channel=Pilot_obet

**Additional context**
Thanks for all your great work on this mod, really enjoying it so far!

**Comment by 747-4EVER** [comment]
Fixed in #306
