### ISSUE TITLE
[REQUEST] Auto update package version in manifest.json

### ISSUE THREAD

**Issue by ozamorowski** [saltysimulations/salty-747#153]
**Is your feature request related to a problem? If so, please describe.**
I lost track which version I already have, and always need to do fresh copy.

**Describe the feature you want implemented.**
Build already add total_package_size to manifest, it could add package version too, but I don't now from where to get version constant.

Your Discord: Olaf#9323

**Comment by ninjomcs** [comment]
we will start incrementing it for stable versions.
