### ISSUE TITLE
[BUG] ND Is Upside-down 

### ISSUE THREAD

**Issue by Zyonix007** [saltysimulations/salty-747#156]
**Version of the mod**
DEV

**Describe the bug**
The ND displays is flipped 

**To Reproduce**
Happens every time 

![image](https://user-images.githubusercontent.com/60050366/110710589-23de1300-81cc-11eb-9f35-36cdd0907c1f.png)

**Comment by ninjomcs** [comment]
this is due to the update, should be fixed soon

**Comment by Zyonix007** [comment]
damn it why they do be breaking everything

**Comment by ninjomcs** [comment]
they're adding features, it is 100% expected that the aircraft mods will break after every update

**Comment by 747-4EVER** [comment]
Fixed in master.
