### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AirbusBoi** [saltysimulations/salty-747#157]
**Version of the mod**
Stable Release

**Describe the bug**
My N1 Throttle Is embedded into the quadrant like its not at the same height as the 2 3 and 4 thrtotle.

**To Reproduce**
Just Use the 747 

**Expected behavior**
None

**Screenshots**

https://gyazo.com/184bf85a482c230f6be227e0da1e9caf?token=51a27539b382690486edf6cd89db9801
https://gyazo.com/0c47d8713b4f85dbd8950171993653e1?token=c01b9056ab85d9e9e473022b27aa0ed8

**References**
https://gyazo.com/948af4ef28913e3cd9f6d352ab77616a

**Additional information**
I believe its both, I have not tried it without the salty simulations mod.

Your Discord: ImMatt#6248

**Comment by ninjomcs** [comment]
fixed by asobo
