### ISSUE TITLE
[BUG] Flaps Drag with Leading Edge Slats

### ISSUE THREAD

**Issue by dcherrie** [saltysimulations/salty-747#159]
**Version of the mod**
Master Dev version at time of post.

**Describe the bug**
When taking off with flaps deployed, it is almost impossible to accelerate above 200 knots and still climb. Once flaps are fully retracted you get a huge boost of thrust to get you to your selected speed. It doesn't matter whether or not you're at Flaps 1 or Flaps 20 for takeoff, can't climb to above 200 knots and still climb. Happens with and without autothrottle engaged.

**To Reproduce**
1. Start flight.
2. Have any flap settings deployed.
3. Take off and try and climb at a normal rate above 200 knots and accelerate to 250 knots without retracting flaps fully.

**Expected behavior**
With flaps deployed and climbing at less than 1500fpm, at full thrust the plane should accelerate.

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Assume so but will need to test. Issue was first introduced with World Update III with the flaps issue. Subsequent updates from Asobo have not fixed the thrust issue.

Your Discord:
davidcherrie#1672

**Comment by DesertRick13** [comment]
Version: Salty :Master, downloaded 3-12-2021

TJSJ>KSEA
Cold and dark start
TOW 917K lb
Flaps 20
N1 max set at TO 99.6
reached 233KIAS when started flaps up.
reached autothrottle max set of 250 KIAS while flaps still retracting

**Comment by dcherrie** [comment]
@DesertRick13 All I do for the Thrust Limit page is select climb to be CLB and not CLB-1. And usually the default SEL is 20 or 30 degrees with an N1 of around 87%. What am I doing wrong?

I also usually don't use TOGA, just move the thrust levels all the way forward.

**Comment by DesertRick13** [comment]
Well, there is another part to the story. I diverted to Denver, because it is really bad weather there right now, and I like to practice challenging conditions. One thing I noticed is when I started to set flaps 5 in level flight at FL090 on my approach to Denver, the throttles bumped way up to keep up. I was doing about 240KIAS at the time. When I went to land, I needed to execute a go-around  because of minimums and got caught in a "coffin corner" where I couldn't generate enough speed to climb with the flaps at 30 until they started coming up and then I didn't have enough lift for my speed, hence the mile-long streak on the ground right near 35R. LW was approximately 780 K lbs (after fuel adjustments made after the diversion) Mind you, I had the spoilers set at detent, and I am,  ahem, sure that didn't help anything, but I think the drag was still too high because of the reaction when I first started lowering the flaps. I will fly again tonight (US Pacific time) or tomorrow and let you know in a little more detail what happens on both ends. 

I used the TO setting on performance, which gave me the 99.6 rating. I always hand fly the initial part of the takeoff and the last 5 NM of the landing, both throttle and yoke/stick.

**Comment by dcherrie** [comment]
Here are 4 tests I did taking off at different weights.

https://www.youtube.com/watch?v=W3aSxr6Qgys
https://www.youtube.com/watch?v=HL9P6zndV0I
https://www.youtube.com/watch?v=KMjEzMXck_A
https://www.youtube.com/watch?v=qfR5iNyg8s0

Conclusion is that there seems to be something limiting the speed with flaps 5 or greater. No matter flying level with flaps 5 or greater, you will not be able to accelerate past 220 knots. 

In the videos, retracting from flaps 20, to 10, to 5 sees little to no acceleration. Retracting flaps 5 to 1, there is a huge amount of acceleration.

I just did a couple of take offs without the mod and you're able to accelerate further with each flaps retraction. At flaps 5 you can comfortably climb and maintain a speed of 235 knots before retracting to flaps 1 or UP.

**Comment by DesertRick13** [comment]
Thanks! I will look at the videos, but I rather concur with your conclusion. I think for comparison I am going to deign to fly just plain vanilla from TJSJ to KMIA and see if the Asobo version has similar issues. It could be like the LNAV/VNAV situation where Salty may have to de-compensate or regress from some of its then necessary changes because of an improving model. This quick hop may be instructional. Happy flying!

**Comment by DesertRick13** [comment]
Flight test for questions of flap drag
TJSJ>TJBQ
Winds consistently +/- 065@10
Model: ASOBO 747-8i
TOW 917 K lbs
Takeoff unremarkable, except that VNAV and LNAV did not automatically engage with engagement of autopilot (Confirmation of a previous observation by DCherrie)
Reduced fuel so weight was @777 K lbs
Level at FL 020 Wind 065/10
Heading 296 deg.
244kts (all airspeeds indicated) flaps 10 N1 86.9 (auto throttle engine setting required to maintain 244kts)
234kts flaps 20 N1 81.6
209 flaps 25 N1 71.4
184 flaps 30 N1 63.5

FL 010 ft. AGL landing configuration (flaps 30, gear down, spoilers detent), heading 176 deg.
167 knots  N1 75.4

Throttle at touchdown (manual) N1 73.5, heading 078 degrees, reference speed +/- 155 kts.

I don’t want to interpret the data too much.
A couple observations: Yesterday at KDEN with Salty’s most recent Dev. LNAV and VNAV did automatically engage, and...
Headwinds were higher (hands too full to recall), flying the needles in landing configuration, aircraft stalled with throttles at maximum power, weight approximately 775K lbs.

Today, upon takeoff from TJBQ (ASOBO) TOW 780K lbs, I did notice a large acceleration upon flaps nearing full retraction

**Comment by Brecherbernd** [comment]
@DesertRick13 @dcherrie "Takeoff unremarkable, except that VNAV and LNAV did not automatically engage with engagement of autopilot (Confirmation of a previous observation by DCherrie)"

Thats the right behavior and has been updated with the latest patch:

"Boeing 747-8 Intercontinental : LNAV and VNAV does no longer engage automatically when activating the Autopilot."

**Comment by DesertRick13** [comment]
Yes, I am aware, and was simply confirming the message sent by DCherrie. Salty's still does automatically engage LNAV and VNAV (at least at the time of my writing the report), and the reason I did my test flight with the plain vanilla Asobo was to compare the characteristics between the two. (see previous conversations in this thread.) Thank you and happy flying!

**Comment by dcherrie** [comment]
@Brecherbernd #160 Check the other bug report.

**Comment by 747-4EVER** [comment]
Changes were made to the flight model.cfg in 1.14.5.0 that haven't been ported yet, including specifically to the flaps. Is this issue still present on the asobo aircraft?

**Comment by DesertRick13** [comment]
@747-4EVER  In my opinion, yes. Honestly, I noticed it more when lowering the flaps at the appropriate speed for approach configuration. When I went from flaps 1 to flaps 5, it almost felt like an arrestor wire for a second, and autothrottles had to really kick in to keep the set airspeed. I think the heavier the aircraft, the less noticeable the effect on takeoff, because a pretty slow rollout and liftoff are to be expected. I haven't flown since last Saturday, and my approach wasn't scientific, but I noticed the takeoff at 917 K lbs had less of the effect than the one at 780Klbs, and both were less dramatic than configuring for approach.

**Comment by DesertRick13** [comment]
For what it's worth, I sent a message to Asobo support.

**Comment by dcherrie** [comment]
@747-4EVER in my version for the past few flights I have done, I made the changes to match the Asobo flight model with the flaps with having the drag lift and pitch scalars all back to one. Salty has them at 1.5 and 0.9 respectively.

It didn't totally fix the issue but it greatly improved the climb to the point where I wasn't on the verge of stalling at 1500 feet whilst retracting the flaps from 20 to 0 at 180-200 knots.

**Comment by DesertRick13** [comment]
@747-4EVER @dcherrie   According to the synopsis of the March 18  development I saw from SimFlightPro, apparently Asobo still thinks they have a problem with this. I think they're going to make an attempt at fixing it in the next release. Hang on!

**Comment by hheexx** [comment]
@dcherrie I have the same bug as you described on default 747. Exactly happening from World Update III.

**Comment by hheexx** [comment]
Fixed by Asobo.
This can be closed.

**Comment by boufogre** [comment]
> 
> 
> Fixed by Asobo.
> This can be closed.

I have just tried, and I still a drag issue for flaps 5 and beyond. How did you test it?

**Comment by dcherrie** [comment]
There is a slight improvement with the default 747 but I can't get the plane to accelerate above 205-210 knots with flaps 5 or more and still climb. Asobo haven't changed any of the flight model or engines (except reducing idle fuel flow by a third) config files.

I'm unsure if they have changed any of the target performance. @hheexx can you elaborate on what you have done?

**Comment by hheexx** [comment]
Well,  I had 2 flights and I thought it was way better but then I had flight last night and had the problem again.
I guess I'm already used to slowing down to 200 before extending flaps 5.

**Comment by dcherrie** [comment]
@hheexx I'm getting used to it too but is still obvious it catapults you when retracting from flaps 5 to 1.

**Comment by boufogre** [comment]
Here is a video illustrating exactly what's happening with the flaps:

[https://youtu.be/uJWS3E_JyeY](url)

**Comment by dcherrie** [comment]
@boufogre So you are saying that at Flaps 5 and beyond, it applies the full amount of drag meant for Flaps 30?

**Comment by boufogre** [comment]
> 
> 
> @boufogre So you are saying that at Flaps 5 and beyond, it applies the full amount of drag meant for Flaps 30?

Yes, that's exactly what I'm saying. The only way to fix this at the moment is to replace, in the [FLAPS.1] section of the flight_model.cfg file, the 21 value for each flaps.n position by 1, 5, 10, 20, 25, 30.

By doing so, you'll restore normal lift and drag for each flap setting.

However, be advised that this will break the animation of the 3D model.

I made a post over at the MSFS forums explaining the bug: [https://forums.flightsimulator.com/t/sdk-q-a-stream-feedback/394224/58?u=boufogre](url)

**Comment by dcherrie** [comment]
@boufogre Changing the drag coefficient to be the same for each slats setting seems to fix it without breaking the animation and also changing the max on ground setting. There is still a little bit of a sling shot when going from flaps 5 to 1 but I can atleast get to a speed of 235 knots at flaps 5.

**Comment by boufogre** [comment]
@dcherrie I need to try this again. I remember trying your solution but having the problem anyway. Just by curiosity, which drag coefficient did you use?

**Comment by dcherrie** [comment]
@boufogre The drag coefficient in each slats setting.

**Comment by dcherrie** [comment]
@boufogre have just started a pull request #183.

**Comment by DesertRick13** [comment]
I put the settings back to 1, 5, 10, etc in the flight_model.cfg. It is nice to not be thrown through the windshield on deployment of flaps 5!

**Comment by dcherrie** [comment]
> I put the settings back to 1, 5, 10, etc in the flight_model.cfg. It is nice to not be thrown through the windshield on deployment of flaps 5!

Is there still a bit of a kick doing that? I find going into Flaps Up in my PR, there is still a accelerate forward a bit.

**Comment by DesertRick13** [comment]
I do notice the approach/decel to be a quite a bit smoother.  I think I see your point on takeoff/accel, but my departures have been ones involving climbs and turns, so I haven't been able to really pay as much attention to that as I have wanted. I will continue to modify each of the master or releases with this until it is fixed.

**Comment by 747-4EVER** [comment]
Fixed by asobo in SU4.
