### ISSUE TITLE
[BUG] LNAV & VNAV when engaging Autopilot after Asobo says its fixed.

### ISSUE THREAD

**Issue by dcherrie** [saltysimulations/salty-747#160]
**Version of the mod**
Latest Master Dev at time of post.

**Describe the bug**
LNAV and VNAV engage no matter what you have selected when engaging autopilot.

**To Reproduce**
1. Select HDG HOLD, ALT HOLD and SPD
2. Engage Autopilot
3. Watch LNAV and VNAV engage instead.

**Expected behavior**
Whatever is selected should engage once turning on autopilot. If nothing is selected I believe ALT HOLD and HDG HOLD should engage.

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Unsure, have not had time to test.

Your Discord:
davidcherrie#1672

**Comment by DesertRick13** [comment]
It would be nice if the PR people and the Development people at Asobo confirmed details before releasing them! Comment sent to Asobo

**Comment by dcherrie** [comment]
@DesertRick13 have confirmed it is not an issue in the Asobo version. So there is something conflicting in the mod to always enable LNAV and VNAV.

So for once Asobo actually fixed something when they said they fixed it.

**Comment by 747-4EVER** [comment]
Should be fixed once 1.14.5.0 changes are ported to Salty.
