### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by realfakeplanes** [saltysimulations/salty-747#168]
**Version of the mod**

Stable release 

**Describe the bug**

The FMC only provides one transition which is not correct for any actual transitions on an arrival. 

**To Reproduce**
1. Select KCLT as your arrival airport
2. Choose the CHSLY4 arrival

**Expected behavior**
Only one transition will be shown for each runway and no matter which runway is selected, the only actual transition is COUPN. COUPN doesn't show as one of the options. 

**Screenshots**

![image](https://user-images.githubusercontent.com/82298164/114290212-a9a2e780-9a32-11eb-8f71-2e57786fe24c.png)

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
generic navdata / fpm issue
