### ISSUE TITLE
[BUG] Vertical ILS G/S Diamond Missing

### ISSUE THREAD

**Issue by dcherrie** [saltysimulations/salty-747#184]
**Version of the mod**
Latest version as of the mod at the time of post.

**Describe the bug**
When doing an ILS approach, LOC diamond is displaying however the G/S diamond doesn't.

**To Reproduce**
1. Do an ILS approach.

**Expected behavior**
Should have a G/S diamond.

**Additional information**
Presented in the recent updates in the past week from SALTY. Unsure if related to any Asobo update.

**Comment by 747-4EVER** [comment]
Fixed in #176.
