### ISSUE TITLE
No virtual cockpit at all

### ISSUE THREAD

**Issue by Rockwell1799** [saltysimulations/salty-747#191]
Hello 
I downloaded the latest version of the release, put it in the community folder and I get this:
https://imgur.com/49Mx4ep

https://imgur.com/BmC9IvH

I don't have any other 747 mod in the community folder.Can someone help me get this fixed?
Thanks in advance

**Comment by ninjomcs** [comment]
empty your community folder completely (that includes liveries and other mods, literally everything) and report back

**Comment by kgavionics** [comment]
I moved everything in the community folder expect the salty747 and I have the same problem!

**Comment by ninjomcs** [comment]
now remove salty and see if the issue persists

**Comment by Rockwell1799** [comment]
I removed salty and I got the stock 747-8 working fine!

**Comment by ninjomcs** [comment]
which version of the sim are you running? this is the first time anyone has reported this issue

**Comment by Rockwell1799** [comment]
My MSFS version is 1.14.5.0

**Comment by ninjomcs** [comment]
why are you not on the latest version? as far as i know legit copies of the game force you to update

**Comment by Rockwell1799** [comment]
> 
> 
> why are you not on the latest version? as far as i know legit copies of the game force you to update

I had fps problem with the latest version, the best fps i got is with this version.To prevent msfs updates, I simply prevent it from connecting to the internet.

**Comment by Rockwell1799** [comment]
I'll wait for the next update to test your mod.thanks
