### ISSUE TITLE
ATIS Does not Work [BUG]

### ISSUE THREAD

**Issue by moxiejeffdallas** [saltysimulations/salty-747#192]
**Version of the mod**
 master

**Describe the bug**
 When I make a request for any ATIS airport in US, it always comes back "ATIS is not available" -- it doesn't work.

**To Reproduce**
1. Spawn into KDFW
2. Load up the 747... then go to ATIS, create a request for DEPARTURE or ARRIVAL airport (either or)
3. Pull up the message once it's received, it shows blank info or says ATIS isn't available."
4. 

**Expected behavior**
 The latest dev notes say Simbrief and ATIS are implemented. Simbrief works, ATIS does not. 

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod? Only in mod

Your Discord: moxiejeff

**Comment by parlock** [comment]
This should be fixed now with this pull request #221
