### ISSUE TITLE
[BUG]FMC remains blank screen

### ISSUE THREAD

**Issue by 39crauds33** [saltysimulations/salty-747#197]
**Version of the mod**
latest version 3.0 installed today

**Describe the bug**
Aircraft spawned in Cold and Dark state.  Turn on battery: no CDU display; Activate External power:  still no CDU display;  Start APU: still no CDU display.  Restarted flight with same results.  Then I restarted computer and MSFS but still got same results

**To Reproduce**
1.  Spawn aircraft @ gate in cold and dark state;  any airport
2. 
3. 
4. 

**Expected behavior**
FMS CDU should display anytime aircraft is powered

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?  Only in the mod

Your Discord:

**Comment by bscout9956** [comment]
What version of the mod?
Can you see a slash at the top of the mcdu screen

**Comment by 39crauds33** [comment]
Nothing appears on the screen.  Version is latest v3

**Comment by Deekay8311** [comment]
Same issue for me. No matter what I do. Battery - External power or External power- battery. fmc stays black. interestingly, if I pop up the fmc screen I can see the screen but only on poped up screen not fmc itself.

**Comment by ninjomcs** [comment]
fixed in #225
