### ISSUE TITLE
ENG START Switch LIGHT always ON

### ISSUE THREAD

**Issue by Jack737800** [saltysimulations/salty-747#20]
In the overhead panel, normally when selecting an engine starter the light illuminates and turns off, when the engine starter cut-out. These lights are always on

**Comment by oscnogbal** [comment]
thats actually not true for the 747-8. On the older version (747-400) there was a light showing if the start valve was open or closed. On the 747-8 there is no light anymore.

**Comment by 747-4EVER** [comment]
Seems like this should have been closed a while ago as behaviour is correct as per oscnogbal.
