### ISSUE TITLE
[BUG] IRS begins aligning before the aircraft is receives eletrical power

### ISSUE THREAD

**Issue by crGowen** [saltysimulations/salty-747#204]
**Version of the mod**
Dev

**Describe the bug**
IRS begins aligning as soon as IRS knobs are set to "NAV", regardless of if power is on or not.

**To Reproduce**
1. Start cold and dark
2. Turn all IRS knobs to NAV
3. (optional) Open dev console and check, IRS timer is already counting down
4. Turn on the battery and APU, observe the IRS TIME TO ALIGN was already counting down before powered on

**Expected behavior**
IRS begins alignment once powered

**Comment by boufogre** [comment]
It would be nice to implement different counters, one for each unit.
