### ISSUE TITLE
[BUG] FMC doesn't recognize valid, AIRAC 2104, waypoints, STARs and approaches.

### ISSUE THREAD

**Issue by g00gas** [saltysimulations/salty-747#205]
**Version of the mod**
stable 0.30

**Describe the bug**
The FMC Routing menu doesn't show me BLAKA4A arrival for YSSY, also the FMC doesn't recognize the existence of GAMBL waypoint, despite the latest AIRAC from Navigraph installed. The Simbrief import also struggles with the trip.

**To Reproduce**
1. Spawn at YSSY in a cold&dark state.
2. Power up the electric system of the airplane.
3. Align the IRS'.
3. Initialize the flight (position, departure and arrival airport etc.)
4. Input the arrival FISHA8.ENTRA - works ok.
5. Input the airway (H133) - works ok.
6. When inputting the GAMBL as the end-waypoint of the airway, the FMC displays: "2ND INDEX NOT FOUND".
7. When trying to select the BLAKA4A arrival via DEP/ARR, only BLAKA4X is present, which shows ILS approaches, which according to Navigraph is incorrect, since BLAKA4X only supports RNAV approaches.
8.  Restart the flight and initialize the route with Simbrief - get presented with the same problem.

**Expected behavior**
The ability to input valid points of airways is expected; such as the ability to choose all SIDs.

**Screenshots**
BLAKA4A arrival missing.
![BLAKA4A](https://user-images.githubusercontent.com/84047607/117893866-87afb580-b2bb-11eb-97b0-73cf68123b1e.png)

GAMBL waypoint not inputtable.
![GAMBL](https://user-images.githubusercontent.com/84047607/117893870-88e0e280-b2bb-11eb-8490-94665c84bf6c.png)

Current AIRAC installed on my sim.
![airac](https://user-images.githubusercontent.com/84047607/117894065-d9f0d680-b2bb-11eb-8b9e-fd7a9bdf0bc0.png)

**References**
The route is: RWY07/FISHA8 ENTRA H133 GAMBL H66 BLAKA BLAK4A/19R

**Additional information**
Q: Is this bug present in the default 747-8, or only in the mod?
A: I wouldn't know, however the whole trip is programmable in the A32NX from start to finish.

From what I recall, while using the mod some odd 3-4 months ago, I also had problems with missing procedures when flying out of EPSC and arriving in EPPO.

Your Discord: tr1pled#4285

**Comment by Funda86** [comment]
Same problem. Simbrief doesn't load all the waypoints (not even the default flight planner). They are all listed in Route page but not in legs page

**Comment by burhan** [comment]
Having the same issue here as quite a few the waypoints are missing in my flightplan as well.

**Comment by petere190** [comment]
Also found that directs don't work, and once a STAR has been entered,  no way to edit or change the routing.
