### ISSUE TITLE
[BUG] FMC does not have working buttons

### ISSUE THREAD

**Issue by Gman202** [saltysimulations/salty-747#211]
**Version of the mod**
 Latest stable release

**Describe the bug**
 Used MSFS flight planner for IFR flight from Narita to KLAX. Unable to use RTE, LEGS or RAD NAV button to access and enter data in those menus

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
 RTE button shows new screen as per ASOBO 747, LEGS button shows usual info between waypoints RAD NAV button shows screen and manual entry of ILS frequencies etc

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod? No only in the mod

Your Discord:

**Comment by ninjomcs** [comment]
clear out your community folder and report back

**Comment by Gman202** [comment]
Cleared out the community folder. Still the same unless I am making a procedural error. Not had time to look at this as been dealing with personal issues
