### ISSUE TITLE
FMC auto-adding LEGS vectors. Can't be deleted. | Non-working "press" buttons on fuel pumps - see screenshot | Co Route not functional?

### ISSUE THREAD

**Issue by Qpanther0** [saltysimulations/salty-747#213]
**Version of the mod**
Latest Dev version, date: 05/18/2021

**Describe the bug**
After filing a flight plan the FMC will add RTE vectors as should. RTE vectors do however tend to get duplicated: making you do a 360 degrees turn or 180 because he was past point B and returns to point A for no reason, apart from a "misplaced" vector.

**To Reproduce**
1. Setup flight plan in session (not menu)
2. File everything: RTE, Flaps, FL
3. Check points via PLN, if no issues showing, add or delete 1 RTE vector and check again.
4. Deleting a "misplaced" vector is barely achievable: delete it like 5x and execute after each deleted attempt to make it work eventually.

**Expected behavior**
It should show that vectors go as following: A, B, C, A, C

**Screenshots**
https://gyazo.com/6864ccb5ab4f41f45db135d088e1bf9f (Screenshot Navigation PLN Mode)
https://gyazo.com/077c8a802c81f2ea000784d3419376e3 (Screenshot FMC RTE PLN Mode)
https://gyazo.com/6b8881eeb01d5a2b65659e9a8492834b (Screenshot broken lights fuel pumps - see left end where it is even misplaced)

**Additional information**
I assume both, never flown the default version so can't tell 100%

Your Discord: Qpanther#9999 (I'm also in the salty server)

**Comment by DesertRick13** [comment]
You may already know this, but the "press" buttons that are over main 1 are really for the CTR fuel tank pumps. They are functional, but the lights are misplaced. This is a Salty bug, as Asobo's has them placed correctly.

**Comment by Qpanther0** [comment]
> You may already know this, but the "press" buttons that are over main 1 are really for the CTR fuel tank pumps. They are functional, but the lights are misplaced. This is a Salty bug, as Asobo's has them placed correctly.

I do, didn't know it's a Salty bug though, thanks for the input! :)

**Comment by ninjomcs** [comment]
fixed in dev
