### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by svenbremen** [saltysimulations/salty-747#216]
**Version of the mod**
**Latest**

**Describe the bug**
**When starting a flight directly from the runway, everything works fine. But: Wen starting at the gate, aircraft has to be switched on manually, the navigation screen stays blank, only showing a square with "MAP" in it. No WPs, routes, airports layouts, weather radar etc can be shown.**

**To Reproduce**
1. Just start your flight from the gate.

**Expected behavior**
**Should work as it does when starting flight directly on the runway.**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
this is intended behavior accurate to the real world aircraft and one of the features of this mod. you need to align your IRS by turning the IRS knobs to NAV. in the future, please try to make sure that the bug you are reporting is actually a bug. if you need further help, feel free to ask in our discord.

**Comment by svenbremen** [comment]
Hi,

Thanks for your reply and sorry for not sending an issue but a real function.

But: Where can I find it?

Thanks for your support!

Sven
Am 21. Mai 2021, 15:54 +0200 schrieb Ninjo :

**Comment by svenbremen** [comment]
I am meaning: Where can I find the „Nav“?

Would be really happy to get it working as everything works by far better than the original Asobo A/P…

Sven
Am 21. Mai 2021, 20:45 +0200 schrieb ***@***.***:
