### ISSUE TITLE
APP Mode - false activation of A/Ps

### ISSUE THREAD

**Issue by Jack737800** [saltysimulations/salty-747#23]
When arming the APP Mode, all three APs get engaged

**Comment by 747-4EVER** [comment]
This is normal aircraft behaviour when on approach in LOC & G/S mode. All three autopilots activate in triple channel mode in preparation for autoland when passing 1500 feet.

**Comment by Jack737800** [comment]
Well....this was not an autoland and my ALT was 3000ft before intercepting the G/S. This can´t be right, as the decision for an autoland should be done by the Pilot, not by the plane itself. 
But if you have any documentation that I´m wrong, I would be happy to read it :)  (a good pilot never stops learning)

**Comment by 747-4EVER** [comment]
You can see here that the 3 autopilots are armed when APP is selected. 

https://youtu.be/VjS849ssgrw?t=592

**Comment by Jack737800** [comment]
Nice ! Thanks for the link! 
This must be a specific thing to the 747, or more modern airplanes I guess?

**Comment by 747-4EVER** [comment]
No problem, its the case on all the "brown Boeings" also 757/767/777.

**Comment by Jack737800** [comment]
:D good to know

**Comment by 0Jumpero** [comment]
Issue should be closed.
