### ISSUE TITLE
[BUG] UNABLE TO LOAD CLEARANCE when pressing SEND

### ISSUE THREAD

**Issue by andreda** [saltysimulations/salty-747#233]
**Version of the mod**
 STABLE 0.3.0

**Describe the bug**
Created flight plan in Simbrief, my ID is frajolex. When I press SEND, I receive the UNABLE TO LOAD CLEARANCE message

**To Reproduce**
1. Create FP
2. load game
3. go to FMC, add SIMBRIEF ID frajolex
4.  press SEND

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
your simbrief id is not "frajolex", that is your username. the id is a 6 digit number
