### ISSUE TITLE
[BUG] Unable to edit route or use directs

### ISSUE THREAD

**Issue by petere190** [saltysimulations/salty-747#235]
**Version of the mod**
Stable>

**Describe the bug**
<!-i am unable to direct to waypoints further along the route, also adding a fmc arrival transition messes up the route-->

**To Reproduce**
1. 
2. 
3. 
4. 

**Additional information**
MOD stable version ?

Your Discord:

**Comment by 747-4EVER** [comment]
Fixed by #240
