### ISSUE TITLE
[BUG] AIRPLANE BANKS TO THE LEFT OR RIGHT EVEN WHEN FLYING STRAIGHT!

### ISSUE THREAD

**Issue by dtribbs1234** [saltysimulations/salty-747#236]
**Version of the mod**
 Stable Release 0.3.0

**Describe the bug**
 When I am flying my flight plan  in the plane, when I am flying straight, sometimes the airplane banks to the left or right and still flies straight.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
 It is supposed to fly straight without banking to the left or right and be centered.

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
As far as I am concerned, it happens in both.

Your Discord: GamePlay Works#4127

**Comment by ninjomcs** [comment]
too little information. check your deadzones
