### ISSUE TITLE
[BUG]It makes the Bredok3D Boeing 737 MAX's fmc screen blank

### ISSUE THREAD

**Issue by neo16ye** [saltysimulations/salty-747#237]
**Version of the mod**

    stable release and dev version
**Describe the bug**

**To Reproduce**
1. It makes the Bredok3D Boeing 737 MAX's fmc screen blank
2. After I removed the salty-747,the 737's fmc screen came back.
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by ninjomcs** [comment]
this happens because the bredok3d 737 uses default avionics. i would suggest contacting them and telling them to make a proper aircraft, or wait for the hard-fork we'll be doing in the future
