### ISSUE TITLE
EICAS screen is static/blank

### ISSUE THREAD

**Issue by picklertune** [saltysimulations/salty-747#241]
**Version of the mod**
 Stable

**Describe the bug**
 EICAS screen does not update after installing. Reinstalling the 747 from content manager and removing/reinstalling salty 747 does not solve the issue.

**To Reproduce**
1. Install Salty 747 in communities folder
2. Launch MSFS
3. Start either from ramp/gate/runway
4. EICAS screen is frozen and does not update when adjusting throttle  

**Expected behavior**
 EICAS should indicate throttle position and all other instrument information

**Screenshots**
 
![image](https://user-images.githubusercontent.com/80365924/125345031-02319b80-e326-11eb-87b5-a04e61323eca.png)

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod? only in the mod

Your Discord: alopolo

**Comment by ninjomcs** [comment]
reinstall the plane, try dev, try emptying out your community folder

**Comment by picklertune** [comment]
nothing works. i reinstalled the whole game. i went back to version 0.2.8 and it's fine now but newer version dont seem to be compatible with latest patch.
