### ISSUE TITLE
[BUG] Plan is not visible in VRF map and cannot be used with ATC

### ISSUE THREAD

**Issue by zahgol** [saltysimulations/salty-747#257]
**Version of the mod**
New 747-salty dev version (with dev version prior to 16th July I had no problems)

**Describe the bug**
When entering flight plan to MCDU it does not sync with in-game VRF map or systems. Things like requesting flight plan, taxi and take off subsequently do not work/is no option to chose them since sim is not aware of plan.

**To Reproduce**
1. Installed latest dev version 2021-07-18T22:30:31+00:00 from previous dev version
2. Installing 0.3.0 removed any problems
3. If I remove it and put back dev version problem reoccurs immediately

**Expected behavior**
Plan should be visible in VFR to use with in-game ATC I assume.

**Screenshots**
dev version
![image](https://user-images.githubusercontent.com/87678853/126245357-d318d2f6-0060-49af-a5f1-6f49fae1a685.png)
version 0.3.0
![image](https://user-images.githubusercontent.com/87678853/126246768-8adde408-b85e-4cb0-9202-14cf09b196dc.png)

**References**
N/A

**Additional information**
This bug is only present with 747-salty version.
I tried dev, rc1 and rc2 all have same problem.

**Comment by giridat** [comment]
This is due to the new FPM system being used from the Working title team. Currently has no known fix.
