### ISSUE TITLE
Unable to change autobrakes.  Knob does not move

### ISSUE THREAD

**Issue by demariners** [saltysimulations/salty-747#269]
I am noticing since SU5 the autobrakes knob does not move.  I have deleted the mod and then reinstalled it and the same thing occurs.  I have confirmed that it works with the mod uninstalled.  I am using the latest dev build here on github from readme.

**Comment by ninjomcs** [comment]
this was fixed yesterday. redownload dev and make sure you are on the latest version

**Comment by demariners** [comment]
Is there a way to check this?  I will re download again from the readme unless I am not downloading from the right place.

**Comment by giridat** [comment]
https://github.com/saltysimulations/salty-747

Scroll until you see the development build. 
It has been updated and issues have been fixed.
