### ISSUE TITLE
[BUG] nO

### ISSUE THREAD

**Issue by k8cpachuck** [saltysimulations/salty-747#280]
**Version of the mod**

4.0 Stable

**Describe the bug**

Gauges are Blank

**To Reproduce**
1. Fly the plane
2. 
3. 
4. 

**Expected behavior**

Suppose to be there, lit up

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Mod

Your Discord: none

**Comment by giridat** [comment]
1. You have the wrong version.
2. You have incompatible livery.

https://github.com/saltysimulations/salty-747/releases/tag/v0.4.0

Use this link wipe any previous version and install this fresh.
