### ISSUE TITLE
MS flight plan not imported into FMC

### ISSUE THREAD

**Issue by truespirt14** [saltysimulations/salty-747#284]
**Version of the mod**

Latest dev version

**Describe the bug**

MS flight plan doesn't appear to get imported into FMC when starting powered up, on the runway.

**To Reproduce**
Create a flight plan in the game using the world to select departure & arrival with the 747 to start on the runway.  Once the flight loads, the flight plan will be visible in the VFR window, but no legs are present in the FMC, not even origination or destination airports.    Any steps needed to import MS flight plan, without having to use an outside source like SimBrief?

**Expected behavior**

What's expected to happen is what happens when the mod is not loaded.  The flight plan and its legs should be present in the FMC as what you configure at the start of the flight.

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
This is present only in the mod.

Your Discord:

**Comment by ninjomcs** [comment]
from our discord:

Due to the implementation of the WT FPM, it is no longer possible to use the default world map flight planner or default ATC with the Salty 747. We recommend using SimBrief and a network like VATSIM or IVAO as a substitute.
