### ISSUE TITLE
Can't set Approach minimums "DH or RAD"

### ISSUE THREAD

**Issue by VCC18DT-Hornet** [saltysimulations/salty-747#29]
The 748 is unable to set the Approach minimums for ILS/RNAV approaches, also it lacks the GPWS Minimums Callout
![Desktop Screenshot 2020 09 23 - 15 54 16 54](https://user-images.githubusercontent.com/71790741/94063076-95104200-fdb5-11ea-8780-1a898db3c6c2.png)

**Comment by Jack737800** [comment]
Douple post, already reported! See below

**Comment by ninjomcs** [comment]
#19
