### ISSUE TITLE
Flightplan not available in FMC

### ISSUE THREAD

**Issue by svenbremen** [saltysimulations/salty-747#297]
**Version of the mod**
<0.4>

**Describe the bug**
<After setting up a flighplan with the default MSFS flight planner the flight plan is not being displayed in the FMC. No waypoints shown or in the LEGS / NAV list.>

**To Reproduce**
1. Set up flightplan with MSFS default flightplanner
2. Check if flightplan is available in FMC - it's not. :-)

**Expected behavior**
<Up to 0.3 and before the last MSFS update the flightplan was correctly transferred to the FMC.>

**Screenshots**

**References**

**Additional information**
<No problem with default 748, only when using salty.

Your Discord:

**Comment by ninjomcs** [comment]
this is not a bug, if you want to explicitly enable world map flight planning you need to go to salty settings, misc and enable FP sync. it is disabled by default as it is not recommended.
