### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CL38** [saltysimulations/salty-747#299]
**Version of the mod b747 SALTY 0-4-0 on MSFS 2020

**Describe the bug**
FMC: when I activate the Route LEGS ACT RTE 1 LEGS page the speeds are not displayed, only the ALTs

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
All SID, Road, STAR speeds should be calculated by the FMC

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by giridat** [comment]
This will only be possible with a fully working VNAV system which currently isn't developed and will take time to develop. 
It's expected in future.
