### ISSUE TITLE
[BUG] TCAS doesn't work

### ISSUE THREAD

**Issue by motishow** [saltysimulations/salty-747#300]
I have isntalled the las t version of mod but TCAS doesn't work , the traffic doen't appear at radar .
Can anyone confirm if TCAS is working correctly 
I have set a range to 20 in the radar
thanks

**Comment by giridat** [comment]
TCAS has become a bit buggy after SU5. 

A known issue.

**Comment by motishow** [comment]
thanks a lot , this mod is phantastic hope you can fix the TCAS in the next update.

**Comment by giridat** [comment]
It works partially and is a known bug.

**Comment by ninjomcs** [comment]
TCAS should work after the TFC button is pressed.

**Comment by motishow** [comment]
it s known bug and people says that doesn't work after SU5

**Comment by motishow** [comment]
where is the TFC button in B747? 
![Captura](https://user-images.githubusercontent.com/88205422/131247830-ecc9b912-f5e2-4c5d-8383-70ff1e648966.JPG)

**Comment by ninjomcs** [comment]
it's on the range knob
