### ISSUE TITLE
[BUG] Stable version….The Localiser…..when on Vatsim..I am vectored for approach and so the Approach is a deviation from the Magenta coloured flight plan…So when heading to intercept the Approach path to the runway..the Localiser button does not capture the localiser in this scenario of vectoring and only works when tracking the Magenta coloured course.

### ISSUE THREAD

**Issue by terryherenow** [saltysimulations/salty-747#312]
**Version of the mod**

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord:

**Comment by giridat** [comment]
It is an Asobo bug you need to keep clicking between Loc and app button 4-5 times to get it functioning it's an annoying Asobo bug. 
Please use discord for more support and next time write the bug according to the format. 

Thanks

**Comment by terryherenow** [comment]
Right..sorry didn’t realise I didn’t follow the format.Now the good news...I manually typed the Frequency and Course Direction into the Rad/Nav and it worked when you click the Localiser button...👍👍


Sent from Yahoo Mail for iPad


On Saturday, September 11, 2021, 9:39 am, Giridhar Raut ***@***.***> wrote:




It is an Asobo bug you need to keep clicking between Loc and app button 4-5 times to get it functioning it's an annoying Asobo bug.
Please use discord for more support and next time write the bug according to the format.

Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
