### ISSUE TITLE
[BUG] HOLD light for HDG mode doesn't go out

### ISSUE THREAD

**Issue by Nyxtorm** [saltysimulations/salty-747#316]
Hello,

When I reactivate LNAV mode or switch to Heading SEL mode, the HOLD light in heading mode doesn't go out. I'm new to Boeing, maybe it's intentional but it doesn't seem logical to keep this light on.

![image](https://user-images.githubusercontent.com/20800786/133430932-a3081801-9166-4c31-bf73-8d24aa583673.png)

I use the last dev version.

Thanks for your help and sorry for my English ! ✈

**Comment by giridat** [comment]
Hi, that's not intentional but yes that can occur. 
You can try turning off FD and turn it back on that'll hopefully fix it.

**Comment by Nyxtorm** [comment]
Hi @giridat,

Thank you for your answer. Indeed, good idea. So, my workaround is :

- Disable F/D
- Use selected HDG mode (light goes out at this moment)
- Enable F/D
- Push LNAV and VNAV again

**Comment by ninjomcs** [comment]
Can't reproduce. Make sure you have the latest dev version (redownload it), and if you still have the issue create a new issue with the proper issue template (the form) with detailed steps on how to reproduce.
