### ISSUE TITLE
Taxi Light illuminates cockpit

### ISSUE THREAD

**Issue by Jack737800** [saltysimulations/salty-747#32]
During night time (and I guess of course during day time), the taxi light illuminates the cockpit, which also can be monitored during landing gear extension/retraction.

**Comment by ninjomcs** [comment]
Was this not fixed by #11?

**Comment by Jack737800** [comment]
Oh sorry, this may be, but I haven´t installed any mods, yet. I also haven´t read anything about it in the "Update-readme" file.
I´m just collecting and trying to report new things, to help you to improve this lovely plane :)

**Comment by nobodyn0se** [comment]
Fixed by #11 
Clean install the mod and let me know.
