### ISSUE TITLE
[BUG] Right COMM doesn't work

### ISSUE THREAD

**Issue by DanP77** [saltysimulations/salty-747#323]
### Version

Dev. Version of 20/09/21

### Describe the bug

![image](https://user-images.githubusercontent.com/72685565/134492681-4084cb6e-e752-41d4-9864-f94d9600d265.png)

As by screenshot the right radio panel is off

### Expected behaviour

Radio Panel available and usable

### Steps to reproduce

Switch on the airplane

**Comment by ninjomcs** [comment]
unable to reproduce

**Comment by DanP77** [comment]
Are you telling me that I'm the only one with this issue?
