### ISSUE TITLE
Performance degradation over longer flights

### ISSUE THREAD

**Issue by hardeebees123** [saltysimulations/salty-747#333]
### Version

latest dev

### Describe the bug

I'm experiencing issues with framerate drops on longer flights with the Salty 748 (and incidentally with the Heavy Division 787, but not to the same degree with the A32NX). After around 3-4 hours of flight (and realtime rate) my framerate drops from around 50fps to 10fps. In combination with the framerate decline over time, my GPU also appears to be working a lot less hard — the fan is silent by the time it's reached 10fps.

I can immediately fix this performance issue by loading dev mode, opening the aircraft switcher dialogue and reselecting the same aircraft. As soon as the aircraft reloads, my FPS return to 50+fps for another 3-4 hours before performance degrades again in the same way.

Because I haven't experienced the same problem (to the same degree at least) in the A32NX, and because I can immediately resolve it by reloading the same aircraft mid-flight, I wondered whether it was being caused by a memory leak on the aircraft mod / displays etc rather than the base sim itself?

### Expected behaviour

No framerate degredation over time, or if there is, I wouldn't expect the reloading of the aircraft mid-flight to resolve the issue.

### Steps to reproduce

1. Fly 3+ hours
2. Note framerate degredation
3. Reload the same aircraft from the dev mode aircraft selector without leaving the flight
4. Observe immediate restoration of original (good) framerate.

### Your Discord

JuliusCaesar2000

**Comment by SamFober** [comment]
Have you tried completely disabling AI traffic? When I did that I got my frame rate back to normal.

**Comment by giridat** [comment]
The performance degradation is due to memory leak in the default weather engine. It doesn't unload the weather of the regions that you have passed and that keeps on pilling up throughout your flight causing this issue. This was confirmed by one of our contributors that using a different weather engine like rex weather should solve this. This is a sim issue.

**Comment by hardeebees123** [comment]
Thanks for the quick responses. @SamFober: I did try disabling all AI and realtime traffic, but this made no difference in my case.

@giridat: So given the behaviour I experience (where the fps resolves itself when reloading the aircraft) are you sure that the weather causes this issue? As I am not leaving the flight when I reload the aircraft. The weather appears to remain visible and loaded, only the aircraft reloads in midair. Does that then somehow trigger a clearing of the weather cache in the background at the same time?

**Comment by giridat** [comment]
From what can be done is you can save your flight and restart the sim but even that won't make a huge difference as to changing the weather engine for the time being. I tried restarting and reloading the save flight it worked for sometime but the issue was back in no time.

**Comment by hardeebees123** [comment]
Just to clarify, the solution I noted (and this has been reproduced multiple times) is that I do not quit or save the flight. I simply:

- Load dev mode,
- Open the Aircraft Selector dialogue,
- Keep the currently selected aircraft highlighted, and click Load

The old aircraft unloads, the new one reloads, and my FPS returns to 50+ from the ~10fps I was experiencing before. I retain the high FPS for a further few hours before needing to repeat the procedure.

This implies to me (admittedly, not knowing much about the MSFS codebase) that there is something in the aircraft itself that is causing the slowdown, and that once unloaded and reloaded (without unloading or reloading the current flight/sim session) resolves itself consistently and reliably each time I have faced this issue.

**Comment by hardeebees123** [comment]
I'm going to try another long distance flight today, with using the clear skies weather theme and will report back on the performance.

**Comment by hardeebees123** [comment]
So...

- I flew a 7-hour flight with only the clear skies weather theme. Starting with 60+fps. After around 4 hours of flight the frame rate drop was noticeable (but not as bad as the 10fps I got before). This time I was down to around ~20fps.

- I reloaded my aircraft mid-flight as described above, but saw no significant framerate improvement (23fps up to around 25fps).

- I then turned off realtime AI traffic as suggested above, and that did give an immediate jump back up to 60+fps.

- I was able to continue the flight for the remaining 3 hours with no significant drop-off in FPS.

I think in the first flight that the real world weather issue you described above was masking the FPS drop-off caused by the Realtime AI as well. Which is why the FPS didn't improve when turning off AI. However, I'm still unsure why the FPS improved when leaving realtime weather active, but simply reloading the aircraft mid-flight.

I think I'll have another go and leave Realtime AI traffic OFF, and keep Real World Weather ON, and see if I get any different behaviour.

**Comment by andrew-thox** [comment]
I've also experienced this bug on flights of 6+ hours with the Salty 747. I haven't tried the default 747 but I've done similar long flights with the default 787 and PMDG DC-6 and have not had the same problem.

**Comment by globin** [comment]
Has anyone noticed issues occuring while passing the anti-meridian? I have a feeling that my frame drops have started to occured mostly close to crossing it? This specific issue I haven't had with the 787 or A320

**Comment by DanP77** [comment]
> Has anyone noticed issues occuring while passing the anti-meridian? I have a feeling that my frame drops have started to occured mostly close to crossing it? This specific issue I haven't had with the 787 or A320

In my case no.

**Comment by stmihajlo** [comment]
Try changing the destination on the Flight Assistant tool. There where you can enable the AI pilot. I had the same issue FPS suddenly dropped to 15. Change the destination and turn on AI pilot and after that immediately cancel that destination and turn off the AI pilot. For me that worked for some magic reason. I sounds crazy but I think it's a Asobo bug when rendering the flightplans

**Comment by globin** [comment]
> Try changing the destination on the Flight Assistant tool. There where you can enable the AI pilot. I had the same issue FPS suddenly dropped to 15. Change the destination and turn on AI pilot and after that immediately cancel that destination and turn off the AI pilot. For me that worked for some magic reason. It sounds crazy but I think it's an Asobo bug when rendering the flightplans

That consistantly works with the "normal FPS drops", but there still is a further issue when crossing the anti-meridian, it completely drops for me then and also reduces simrate which I haven't seen with any other FPS issues. Also doesn't happen with the 787 so I'm pretty sure it's an aircraft issue

**Comment by giridat** [comment]
New steps to try and reproduce this issue:

Preconditions: 
1. Try with clear weather and then try with LIVE weather. 
2. Let's also ensure to keep all the AI pilot assists OFF.
3. Finally, try an external weather engine.

To check: 
Whether it's the waypoints in the FMC causing the lag or is it the Asobo weather engine.

1. Try a long haul let's say EGLL - VIDP / EGLL - YSSY and just enter the airports in the FMC so that a DCT Flightplan creates.
2. Same long haul with proper waypoints entered.

**Comment by DanP77** [comment]
At this point I will wait after SU7 and Mod fix

**Comment by Rijtim1** [comment]
I did a ~5-hour flight a few days ago from ELLX to OMDB on the latest dev version, live traffic, live weather, etc. I didn't experience any performance degradation.

**Comment by chosebine501** [comment]
Hi,

my english is not good but I will try.
I'm doing flights beetween 9h a 15h hours
I had some performance problems.
and the problem was not the addon, but rather the cache of all the online elements.
at the beginning my game was 55 to 80 fps.
after 8 to 12 hours of flight, my fps drops to 5 to 15 fps
my solution, put the game on pause, disable all the online elements and reactivate it.
and the fps come back to 60 to 80.
try this

**Comment by DanP77** [comment]
> my solution, put the game on pause, disable all the online elements and reactivate it.

Interesting!
Can you explain better what did you do?

Thx
D.

**Comment by DanP77** [comment]
> I did a ~5-hour flight a few days ago from ELLX to OMDB on the latest dev version, live traffic, live weather, etc. I didn't experience any performance degradation.

I had the problem after 6 hours... (not a longest time with a 747)

**Comment by chosebine501** [comment]
Hi,
put game in pause, Go to section Data in option, and put to off Online Functionality clic Apply And Save, and goback to on, clic Apply And Save

**Comment by ninjomcs** [comment]
unrelated to salty
