### ISSUE TITLE
[BUG] Pilot and Co-Pilot avatars remain visible in first person

### ISSUE THREAD

**Issue by CameronRoxby** [saltysimulations/salty-747#336]
### Version

v0.4.0

### Describe the bug

The Pilot avatars remain visible in first person mode obstructing the view. Only happens on the 747 and when the mod is installed

### Expected behaviour

Pilot avatars to disappear when entering first person

### Steps to reproduce

I loaded into several different airports including EGKK, KJFK, KLAX, KDFW, EGLL, and EGMC

### Your Discord

TheIncredibleFella#2169

**Comment by depthvader** [comment]
can confirm this issue.

**Comment by ninjomcs** [comment]
turn them off in salty settings -> misc
