### ISSUE TITLE
most recent FS update problems

### ISSUE THREAD

**Issue by jmsmith1480** [saltysimulations/salty-747#343]
### Version

0.4.0

### Describe the bug

After microsoft released their update this morning, interacting with the switches in the cockpit using the most recent stable version of the salty mod are not functioning properly.  For example, when I set stand-by power to auto, the aircraft responds appropriately and the flight deck and screens turn on but the stand-by switch is still in the off location.  I had the same response from every other switch I tried, including the IRS switches and the parking brake.  The simulator responded appropriately but the switch did not reflect it.  I tried un-installing the salty 747 release I had and re-downloaded the current stable release from sim4flight.com and there was no change.  Has anyone else had an issue like this?

### Expected behaviour

when I turn the stand by power switch to the right I expect the switch turn move to stand by as power is supplied to the aircraft, the same with the parking brake, IRS switches, lights, etc.

### Steps to reproduce

ensure the sim is using the most current MSFS update, create a flight, and set the departure gate(I used KSAN to KLAX to create a quick test).  Once the sim loads I tried to prep the aircraft for departure when I had these issues.  I used the flight sim livery provided by microsoft, I have no other mods installed.

**Comment by ninjomcs** [comment]
Fixed in #346
