### ISSUE TITLE
No click spot for HDG SEL

### ISSUE THREAD

**Issue by patryklipski** [saltysimulations/salty-747#349]
### Version

latest dev

### Describe the bug

It seems like there is no click spot available to push HDG SEL button. 

I can select turn rate, heading, but can't push HDG SEL.
Checked from different cameras.

### Expected behaviour

As a captain/first officer, I should be able to push HDG button on top of heading selector on MCP, so HDG SEL mode could be armed.

### Steps to reproduce

1. Just try to engage HDG SEL mode, by clicking HDG pushbutton on top of heading selector knob

### Additional information

WIN10, SU6

**Comment by patryklipski** [comment]
It looks like, the bug only occurs, when cockpit control mode is set to 'Lock'. If I set it to 'Mouse', HDG SEL pushbutton works fine.

**Comment by giridat** [comment]
[To be Closed] 

Not a Bug
