### ISSUE TITLE
Joystick

### ISSUE THREAD

**Issue by Richard-54** [saltysimulations/salty-747#351]
### Version

V0.4.0

### Describe the bug

No joystick movement (in cockpit) in normal MSFS profile or FSUIPS profiles or movement in control surfaces in external views. Thrustmaster Hotas4

### Expected behaviour

Movement of the Joystick internally and externally.

### Steps to reproduce

Load A/C (Cold Start) Gate 80 YBBN

### Additional information

Nil

### Your Discord

Richard-54

**Comment by ninjomcs** [comment]
This is likely a problem with your either your hardware, or something in your MSFS settings.
