### ISSUE TITLE
DEP/ARR button in FMS not providing option for arrival configuration

### ISSUE THREAD

**Issue by abuelo007X** [saltysimulations/salty-747#353]
### Version

latest dev

### Describe the bug

First of all I want to say THANK YOU for all the hardwork this teams has done, on making this very interesting mode

While preparing the FMS, I found out that the DEP/ARR button does not provide the option to include the arrival, while you are entering your flight plan. It only activates when being at cruze altitude and not inmediately, and in some cases never getting activated (not sure exactly what parameters are being impacted). For example I did a very short testing flight departing and landing on the same airport with a cruze altitude of 5000ft (from sea level) and while that was the cruze altitude programmed in the FMS it never show the option to provide arrival configuration, during the whole route

Not sure if I missing any step, but really followed everything it seems need to be done, with no success.

I didn't test stable as there are known issues with SU6, and I know some were already included in the lastest dev version, but before SU6, I'm almost sure (using stable) this options was working as expected

I did search before posting, but unable to find any reference to this possible bug submitted by anybody else (unless I missed something)

### Expected behaviour

Have the possibility to enter not only departure but also arrival information in the FMS, being on the ground or also while flying at any flight level, which also worked in previous versions in the past (including stable).

### Steps to reproduce

1 Configure FMS as expected for your flight plan before route configuration
2 Complete manually or using simbrief integration the route on the FMS, including departure airport, arrival airport and via/waypoints
3 Click on DEP/ARR button, and it will only provide option for Departure, with no alternative to switch between both options

### Additional information

https://user-images.githubusercontent.com/88299309/140874280-a9ba326d-bba3-4b11-844e-613fee0e64af.mp4

### Your Discord

Abuelo007X#0728

**Comment by giridat** [comment]
For getting the arrival it usually activates during approach phase. Else you need to click on the INDEX button on the DEP/ARR page have to fiddle with it a little and it'll work.

**Comment by abuelo007X** [comment]
upss sorry. in previous version just clicking on dep/arr page was bringing that index page, and didn't figure that out by myself in this case on testing the index option.
