### ISSUE TITLE
[BUG] pilot avatars visible in first person view regardless of MCDU setting

### ISSUE THREAD

**Issue by dizzyqueen** [saltysimulations/salty-747#354]
### Version

Latest dev

### Describe the bug

Regardless of selected option in MCDU>SALTY>MISC, pilot avatars (Both pilot and co-pilot) persisting the flight deck.  They also persist through shut down and relaunch of MSFS and PC restarts

### Expected behaviour

Avatars to display or hide pending the applicable option chosen in the MCDU/SALTY/MISC screen

### Steps to reproduce

1. Load aircraft at either rwy (ready for departure) or C&D at parking/gate

2. Change MCDU preference for pilot display

3. Observe that no change occurs regardless of chosen option

4. Reload ac, restart flight, restart sim etc to see that pilot visibility remains unchanged after reload method employed 

### Your Discord

#DizzyQueenCA#8418

**Comment by giridat** [comment]
@mixMugz I believe you worked on this, care to take a look at this please? 

Thanks

**Comment by mixMugz** [comment]
> @mixMugz I believe you worked on this, care to take a look at this please?

Just tested now, and no pilot/copilot in cockpit if not selected in MCDU. Only one way to achieve that using any other mod what overwrite default interior behavior definition.

@dizzyqueen if you click in MCDU through pilot options no any changes for pilot/copilot?

**Comment by mixMugz** [comment]
Additional.
1. Please check with default livery
2. Please check your livery not contain INTERIOR.xml file

**Comment by dizzyqueen** [comment]
Correct, both pilot and co-pilot remain regardless what I do ... Even removing all mods, redownloading salty dev and reinstalling clean causes the issue to persist ... Other items in the cockpit (ex. Irs knobs) are unresponsive as well ... I am at a loss ... The only thing I can think of that I have not done is format and reinstall Windows
⁣--
Best,

Kevin M. Harrington MCDST
***@***.***
Sacramento, CA
M: 916.664.7945

Please consider the impact to the environment before printing this email.​

On Nov 11, 2021, 23:59, at 23:59, Maksim Brykov ***@***.***> wrote:
>> @mixMugz I believe you worked on this, care to take a look at this
>please?
>
>Just tested now, and no pilot/copilot in cockpit if not selected in
>MCDU. Only one way to achieve that using any other mod what overwrite
>default interior behavior definition.
>
***@***.*** if you click in MCDU through pilot options no any changes

**Comment by mixMugz** [comment]
Can you post contend of you Community folder?

**Comment by dizzyqueen** [comment]
Interior.xml in the model ... That is probably the issue .. I just installed a livery that has one

**Comment by dizzyqueen** [comment]
You're a Rock Star, Mr. Mugs ... That fixed all the issues I was experiencing with the 747 .... 8f you ever make it to Northern California, your first few drinks are my treat!!  Thank you, Sir!!

**Comment by mixMugz** [comment]
> Northern California, your first few drinks are my treat!! Thank you, Sir!!

It remains only to somehow get to Northern California =)
