### ISSUE TITLE
AP acts weird and seems to not change modes after take off using TOGA mode

### ISSUE THREAD

**Issue by giridat** [saltysimulations/salty-747#358]
### Version

Latest Dev version

### Describe the bug

After TOGA is activated during take-off roll the AP behaves weird and doesn't "Actually" change the mode, although it seems activated as the PFD indicates. 

Sometimes LNAV doesn't activate but VNAV fails to change the mode according to the phase of the flight and seems to overshoot the V2 speed which it is expected to maintain after takeoff, also the autothrottles seem to be stuck in TOGA mode although the PFD indicates otherwise. 

VNAV sometimes descends weirdly and quite a lot of times I have noticed that if the weight of the aircraft is high like more than 50% the aircraft weirdly descends and likes to nose dive or miss the turns even though the speed seems fine. 

The most common workaround to this issue is to re-enable the FDs, AT and the AP after that you need the rearm the LNAV/VNAV.

### Expected behaviour

The LNAV/VNAV should change modes according to the phase of the flight.

### Steps to reproduce

1. Spawn into any airport and set up a full flight.
2. Arm LNAV and VNAV as per procedure during the taxi or while setup.
3. Taxi to the rwy and perform the take-off run using the TOGA mode by activating from the throttles.
4. After take-off and stabilisation enable the AP.
5. Observe that the LNAV/VNAV shows activated on the PFD but VNAV doesn't seem to be activated as the pitch doesn't adjust nor do the throttles decrease to maintain the V2 speed. Sometimes even LNAV fails to activate.

### Additional information

Please see the attached video link uploaded on google drive for reference. Video size is 480MB reduced from 1.3 GBs.

https://drive.google.com/file/d/1FsWT90B4zdFn1r-pukIdNuerinwlfF_v/view?usp=sharing

### Your Discord

Giridhar Raut#5534

**Comment by giridat** [comment]
https://user-images.githubusercontent.com/61822722/144755054-584c1b51-b0be-4a03-be9f-089616fa0aae.mp4

Also, the ILS is being mean over here, I can't say if this is due to the weather bug cause I didn't notice.

**Comment by 747-4EVER** [comment]
Fixed by #362.
