### ISSUE TITLE
Nothing clickable since SU7

### ISSUE THREAD

**Issue by GhostGCR** [saltysimulations/salty-747#360]
### Version

0.4.0

### Describe the bug

Hello,

after installing Version 0.4.0, no Button in the 747 is clickable with Sim Update 7.

### Expected behaviour

Things like Buttons and Switches should be clickable

### Steps to reproduce

Start MSFS2020 with SU7 and Salty 747 0.4.0

### Your Discord

Schaf#7520

**Comment by giridat** [comment]
Use the development version the stable version is outdated. 

*To be closed*

**Comment by DreadKnight1247** [comment]
Stable version not working well with SU7, Dev version is causing other issues like vfr map not displaying your route. I hope someone comes up with a solution for the stable version 0.4.0

**Comment by giridat** [comment]
Keep using DEV version. Use FP sync in FMC to see your flt plan on the VFR map. DEV has been updated again to fix a main bug.

Current stable is outdated. Please be patient for a new one. 

[To be Closed]
