### ISSUE TITLE
B748 AP problems

### ISSUE THREAD

**Issue by jorgesoo** [saltysimulations/salty-747#361]
### Version

latest dev version

### Describe the bug

After SU7, APP or Loc  Autopilot mode doent engage anymore, they worked OK before.

### Expected behaviour

Once set APP or LOC mode, the auto pilot should follow the GS and LOC and it doesnt 

### Steps to reproduce

Tune ILS freq and course, set AP, set APP or LOC.
The annunciator dosnt show the settings and no auto GS and Loc following works

**Comment by giridat** [comment]
Can't say without video or screenshot, it worked fine for me.

**Comment by jorgesoo** [comment]
I attach 3 cockpit photos, the first is the Salty Dev version, the second the stable version, and the third the Asobo version.
First case (Last Dev version) you can see that APP is selected at the MCP, but it is not reflected at the MFD annunciator, and so it didnt work.-
Second case (Last stable version) AP works OK and APP mode is engaged as seen at the annunciator, and could make an excellent auto ILS aproach.- The problem with this version is that there are no animations for controls, switches, knobs, etc.
Third case (Asobo default version) APP is selected at the MCP, and the annunciator shows it. A ILS auto aproach could be done
In my case previously to SU7, had no problems with APP or LOC mod
![cockpit Salty Stable version](https://user-images.githubusercontent.com/95573476/144754595-25a4a86c-75e1-40c1-b9ec-21d102b0a8ee.gif)
![cockpit Salty Dev version](https://user-images.githubusercontent.com/95573476/144754597-7c0eb56a-e57d-4448-a122-16aee21c19e7.gif)
![cockpit Salty Asobo version](https://user-images.githubusercontent.com/95573476/144754601-19f1e475-e5f7-459b-b710-c2996df19741.gif)
e.

**Comment by jorgesoo** [comment]
Sorry
Photos were uploaded not in sequence
First one: Stable version
Second one: Dev version
Third one: Asobo version

**Comment by giridat** [comment]
Suggest you see this. It's from my DEV version.


From what I think of your NAVRAD page, you should put CRS hdg in both lines, maybe you forgot to select ILS rwy in your DEP/ARR page.

Also, the AP is known to be bugged and is being worked upon.

https://user-images.githubusercontent.com/61822722/144754960-475b5f46-857e-4353-bf18-566de5693a39.mp4

.

**Comment by giridat** [comment]
[https://github.com/saltysimulations/salty-747/issues/358](url)

I have also already posted an issue regarding the AP issues. You can close this one as it comes under that one only, It'll only be a Dupe issue.

**Comment by jorgesoo** [comment]
Thanks for your both replies
I mostly use to fly without a flight plan loaded and always set the course
at the left side of the CDU, and have no problems.-
Cannot open the link to your post about AP you mentioned, Chrome says there
some mistake at the url

**Comment by ninjomcs** [comment]
> Thanks for your both replies I mostly use to fly without a flight plan loaded and always set the course at the left side of the CDU, and have no problems.

This is a bug, but currently you have to have the approach actually set in the CDU.

**Comment by jorgesoo** [comment]
I try that, and you are right, now after the SU7, the only way that auto APP works is setting the aproach at the CDU within a flight plan
