### ISSUE TITLE
Upper Panel: External Power button not working

### ISSUE THREAD

**Issue by CielSolitaire** [saltysimulations/salty-747#366]
### Version

v0.4.0

### Describe the bug

**Upper Panel:** 

> Batt ON; 
> Standby Power AUTO; 
> next >>> my External Power buttons don't show "**Avail**" and when I click them, nothing happens.
> 

In Salty 747 videos I watched the "External Power" buttons are lighting up when Standby Power button is switched to AUTO, showing "**Avail**" first and then when button is pressed, "**ON**" lights up. 
When I do the same, nothing happens. The button cannot be used.

### Expected behaviour

**Upper Panel:** 

> Batt ON; 
> Standby Power AUTO; 
> next >>> my External Power buttons **would show** "**Avail**" 
and when I click them, 
 "**ON**"  **would light up**. 
Then I would pursue the start up procedure.

### Steps to reproduce

1. Open battery cover
2. Click Battery to **ON**; 
3. Switch **Standby Power** to **AUTO**; 
4. Switch **External Power 1** button **from** "**Avail**" **to** "**ON**". 
5. You do the same with **External Power 2**.

### Your Discord

CielSolitaire #2668

**Comment by giridat** [comment]
Use the development version, stable is outdated.

[To be closed]

**Comment by DesertRick13** [comment]
Definitely make sure you have the latest dev.
This also depends on where you are parked. Because I like to run mine as a BCF, sometimes I am parked where there is no external power available, and I have to fire up the APU early to get the rest of the systems powered. Not sure of your situation...

**Comment by ninjomcs** [comment]
> **Suggest to Salty team to disable link to Stable 4.0 and keep disabled until there is a 5.0**

I have gone ahead and temporarily removed it from the readme and added a disclaimer in the github release.

**Comment by DesertRick13** [comment]
Thank you @ninjomics.
