### ISSUE TITLE
ILS approach broken

### ISSUE THREAD

**Issue by runningdavid** [saltysimulations/salty-747#367]
### Version

latest dev

### Describe the bug

The plane couldn't perform ILS approach anymore since the last game update. The plane struggles to follow glide path and in the end just gives up. Disconnecting and then re-engaging AP also doesn't work.

### Expected behaviour

Plane should be able to perform ILS approach.

### Steps to reproduce

1. Load into any flight with destination airport having ILS approach
2. Perform ILS landing at the destination airport

### Additional information

I really like this plane and it has worked incredibly well for me in the past. However since the last sim/world update both VNAV descent and ILS approach stopped working. Is this a Asobo issue?

**Comment by chosebine501** [comment]
I have the same problem

**Comment by giridat** [comment]
VNAV on descend is known to act weird.

I'd advise you to please add a video of how you're performing the approach and landing because without any attachments the Devs would hardly know what's really happening.
