### ISSUE TITLE
[REQUEST] Possibility for a FBW style installer?

### ISSUE THREAD

**Issue by notl3ks** [saltysimulations/salty-747#378]
**Is your feature request related to a problem? If so, please describe.**
N/A.

**Describe the feature you want implemented.**
I'd love to see an installer like the FlyByWire one (Salty Installer?). It would be super handy to have, rather than having to keep manually updating the aircraft. Maybe even consider having it in the FBW installer? Some other developer has theirs in it. It would be great!

**References**
N/A.

**Additional context**
N/A.

Your Discord: N/A.

**Comment by ninjomcs** [comment]
the salty 74s will actually be available to download in the fbw installer whenever they implement the functionality required, so stay tuned!
