### ISSUE TITLE
Salty 747 not showing up on main aircraft selecion screen

### ISSUE THREAD

**Issue by KaiAlben** [saltysimulations/salty-747#387]
### Version

latest dev

### Describe the bug

I just downloaded the recent dev release and pasted the "salty 747" folder into the FS2020 Community Folder.
When reloading the game, the aircraft still won't show up.
What can I do?

### Expected behaviour

The Salty 747 Aircraft showing up as a selectable model.

### Steps to reproduce

It's reproduceable all the time.

### Additional information

<img width="723" alt="Main No salty" src="https://user-images.githubusercontent.com/308332/153356105-898fcc32-d0ec-42c9-a94b-a46274717cc9.png">
<img width="565" alt="Salty folder" src="https://user-images.githubusercontent.com/308332/153356114-cd69e6fe-13ae-4521-b47d-d9e21c07417b.png">

### Your Discord

elchaguarma#6383

**Comment by iamdumdum1234** [comment]
It is a modification for the default Asobo 747, just like what B78XH is to the default Asobo 787, not the A32NX. THIS IS NOT A BUG.

**Comment by KaiAlben** [comment]
Thanks
