### ISSUE TITLE
METAR/TAF report broken

### ISSUE THREAD

**Issue by CosmicRayAero** [saltysimulations/salty-747#388]
### Version

Lastest Dev

### Describe the bug

The latest Dev of the 747 the metar/taf received messages is bugged https://photos.app.goo.gl/Rw5NUjifjqr2TcYb8 this vid is on the 777 but I also checked the 747 and it did the same

### Expected behavior

to show METAR and TAF report 

### Steps to reproduce

FMC COMM go to requests and then go to weather hit request METAR or TAF (click either or) click request and then hit received messages, click on one of the reports and the ATC log comes up.

### Your Discord

[VCC18DT] Cosmic#5513

**Comment by CosmicRayAero** [comment]
here is the B748 FMC again I am using the lastest dev build https://photos.app.goo.gl/uY6mBdPbiZw32KFg7

**Comment by ninjomcs** [comment]
fixed in #394
