### ISSUE TITLE
No trails behind the Airplane

### ISSUE THREAD

**Issue by Thanksforthisawsome747** [saltysimulations/salty-747#391]
### Version

latest dev

### Describe the bug

![trails](https://user-images.githubusercontent.com/99812743/154277575-eecb56fd-33ac-4b59-9256-5f882cfbbb00.png)

First of all thank you for your great work.
Sadly ive noticed that theyre no contrails behind my 747. 
It might be not a big deal but it looks pretty unrealistic :( 
On the default 747 they appear at ~FL380 if iam not mistaken

### Expected behaviour

I expected it to be look like this :P
![yee23](https://user-images.githubusercontent.com/99812743/154278211-8c5daf28-4ead-42b1-ac19-4c4eafb79c0c.PNG)

### Steps to reproduce

start a flight 
Climb to final FL 
After reaching TOC you can see this when you select the outside view

**Comment by giridat** [comment]
This doesn't seem to be a Salty related issue but for me contrails always appear according to the weather. I use Live weather.

**Comment by Thanksforthisawsome747** [comment]
The Singapure Airline livery caused this bug. 
I just selected the Lufthansa Livery and now the contrails are back again xdd 
wtf what a strange bug
