### ISSUE TITLE
Update 8 issues

### ISSUE THREAD

**Issue by jmsmith1480** [saltysimulations/salty-747#392]
### Version

0.4.0

### Describe the bug

After the recent update I could not get the salty sim to work.  There are now pilot avatars for both the Capt and FO, and my screen is trying to look through the animated Capt at the controls.  The buttons do not move when I click them but the expected behavior does(when I hit EXT power the aircraft powers up but the button does not reflect it.)  I have never used avatars for any of my flights or downloaded anything regarding avatars.  I have tried going to the game settings and could change the avatar but could not disable it.  I also found the pilot/copilot options on the FMC on the 747 and made sure it was set to none and restarted the game, only to find the same result.  

I removed the current version of salty sim I had in my community folder, downloaded the zip available on github and it removed the salty sim all together.  Without the salty sim I did not have any issues.   I tried the same flight with the 787(with the heavy mod) and had no issues.  I also tried flying the CRJ-700 and A320 Neo (no mods for either) and they worked as expected.  Is there a setting I need to change or new version available as a work around?  Any help is greatly appreciated.

### Expected behaviour

After I finished updating MSFS I put Salty sim back in the community folder and expected the same flight experience I had before the update.

### Steps to reproduce

1) Remove all items from your community folder
2) Update MSFS and replace the items in your community folder
3) Start a new flight using the salty sim mod, I tried flying out of KSAN
4) Once the game starts, when in cockpit view I had pilot avatars

**Comment by giridat** [comment]
You're on the wrong version, 
https://github.com/saltysimulations/salty-747/releases/download/vdev/salty-747-dev.zip
the development version is the only version in use currently.

**Comment by jmsmith1480** [comment]
that fixed it, thanks!
