### ISSUE TITLE
Addon it's not loading in game

### ISSUE THREAD

**Issue by chosebine501** [saltysimulations/salty-747#421]
Hi
I put[ this](https://github.com/saltysimulations/salty-747/releases/download/vdev/salty-747-dev.zip) the last Development build addon, in my community folder, 
(Steam - C:\Users\<USERNAME>\AppData\Roaming\Microsoft Flight Simulator\Packages\Community)
And this version addon it's not load in game.
regards

**Comment by Timberolic** [comment]
Hello,

Please refer to our Discord and reach out on the support tab. There can be a multitude of issues and figuring it out here will be tedious. 

https://discord.gg/S4PJDwk

**Comment by chosebine501** [comment]
Discord ! hum... Thank you very much...

------- Original Message -------

**Comment by chosebine501** [comment]
To FAQ in Discord :
Q: How do I report bugs, missing features, or inaccuracies?
A: Open a new issue and describe the bug or inaccuracy in detail: https://github.com/saltysimulations/salty-747/issues

??

------- Original Message -------

**Comment by Timberolic** [comment]
Your issue is not a bug. You did not install the aircraft directly, hence I directed you to our Discord.
