### ISSUE TITLE
Ground FMA and FD behaviour not correct

### ISSUE THREAD

**Issue by 747-4EVER** [saltysimulations/salty-747#43]
Still seems to be bugged.

Current ground behaviour with FD on:
![bug](https://user-images.githubusercontent.com/71572892/94364352-80d38a00-00c0-11eb-9395-b9480a38d64f.png)

Correct behaviour:

- TO/GA should be visible as active mode in the FMA (x2 for pitch and roll) as well as any armed modes below (LNAV or VNAV)

- also Flight Director pitch bar should indicate 8 degrees nose up on ground.

**Comment by iFarisKH** [comment]
Working on it
