### ISSUE TITLE
MSFS Steam Edition

### ISSUE THREAD

**Issue by Carbonst** [saltysimulations/salty-747#438]
### Version

v0.5.0 and 2f95bc8

### Describe the bug

The Salty Mod doesn't work on the newly purchased Steam Edition of MSFS. Just purchased last week and none of the Salty mod works. Tried both the stable and development and it doesn't work in any form. Tried running it in dev mode and removed any and all other mods and liveries.

### Expected behaviour

Nothing works, so don't know.

### Steps to reproduce

1. tried both Stable and Development
2. tried in MSFS dev mode
3. removed all other mods leaving only "Salty"
4. Installed both manually and using the installer

**Comment by ninjomcs** [comment]
please use the support channel in discord, as this is not a bug
