### ISSUE TITLE
Can't change speed to knots

### ISSUE THREAD

**Issue by Jacke1012** [saltysimulations/salty-747#45]
After skipping (The travel to function) to decent the speed is in mach and when i click the change button nothing happens. I remember this was a problem in the A32X mod as well but they fixed.

**Comment by FabioMike06** [comment]
Have you already tried to do the same thing without the mod?

**Comment by nobodyn0se** [comment]
@FabioMike06 I tried this with/without the mod on 1.9.3 didn't switch during descent. Once in mach, it cannot be changed.

**Comment by FabioMike06** [comment]
@nobodyn0se At this point I think it's most likely an asobo bug. I don't know if it can be fixed by SaltySimulation.

**Comment by nobodyn0se** [comment]
Might be, I've been unable to figure out what's causing the issue in the code.

**Comment by Jacke1012** [comment]
Ok because I remember it being a problem on the default a320 and the a32x mod but then they fixed it on the a32x. Don't know what they did though

**Comment by DesertRick13** [comment]
![Mach button](https://user-images.githubusercontent.com/73233810/97004480-fbda6580-14f1-11eb-83f0-e36ed2de2904.jpg)
The only solution I have found. An Asobo bug

**Comment by bscout9956** [comment]
https://github.com/flybywiresim/a32nx/pull/739 This? Not sure by the way

**Comment by nobodyn0se** [comment]
@bscout9956 the PR you mentioned only enables the toggle on ground. Above crossover altitude, the A32NX and B748 currently requires manual switch from SPD to MACH and vice versa below crossover altitude. The problem lies with vanilla code. The variable XMLVAR_AirspeedIsInMach correctly shows a value of 1 above crossover, in Autopilot_Subtemplates.xml there is some code dedicated to this switch.

**Comment by DesertRick13** [comment]
The switches I demonstrated in the pictures to change Mach to IAS and vice versa work perfectly fine at altitude. Unlike Asobo, I actually test things before I put them out for consumption.

**Comment by DesertRick13** [comment]
See attached
