### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by airforcethree** [saltysimulations/salty-747#450]
**Is your feature request related to a problem? If so, please describe.**

Yes, I am unable to import coordinates from simbrief. They turn into waypoints that are completely unrelated in location.

**Describe the feature you want implemented.**

The ability to import coordinates from simbrief to use in a flightplan.

**References**

**Additional context**

Your Discord: 

broccol#8074

Negative, thanks :)

**Comment by giridat** [comment]
Please be more specific share screenshots or a video explaining your issue. Thanks.

**Comment by airforcethree** [comment]
here's an example of what i mean: if i wanted to fly this route: KPAE 473008N1200024W 483017N1195959W 483005N1194517W 480509N1194553W 480500N1191506W 483020N1191456W 483013N1185959W 472958N1190004W 472954N1191643W 475511N1191514W 475518N1194558W 473014N1194623W 473004N1200659W KBFI, all of the coordinates, when imported to the fms in the 74s would either not be recognized or be somewhere completely different in the world. i see that some of them are recognized as actual waypoints, but not coordinates. if i could get these coordinates to be points in my flight plan, that'd be great
![747featureexample1](https://user-images.githubusercontent.com/106889965/172028259-bb40356c-dc19-4a4d-b50c-57274a928372.JPG)

**Comment by Timberolic** [comment]
Please refer to this image as to inputting coordinates as waypoints.
![E49AE2C4-C423-40C7-AE5C-E6C9FA3ECA7D](https://user-images.githubusercontent.com/97812083/172028314-65c26692-8bde-484c-875f-8dcf019e4370.png)

**Comment by airforcethree** [comment]
Yes, but I am trying to import coordinates from simbrief.

**Comment by Timberolic** [comment]
That's because SimBrief has a different format for coordinates. You will unfortunately be required to do it manually.

**Comment by airforcethree** [comment]
That's my issue then, thanks.
