### ISSUE TITLE
MAINT menu on FMC is empty, can't import simbrief

### ISSUE THREAD

**Issue by xhemp** [saltysimulations/salty-747#460]
### Version

latest dev

### Describe the bug

Just thought I would fly the 747 after the PDF has been rewritten but when I choose the plane on MSFS and spawn, my MAINT menu is empty and I can't import anything from simbrief.

### Expected behaviour

To be able to see the salty menu on the FMC and to import simbrief flight plans.

### Steps to reproduce

I have tried to update using the FBW installer, also tried to delete the folder on my community folder and download from scratch to no avail.

**Comment by giridat** [comment]
Hey, connect with us on discord for support:

https://discord.gg/xRvKvQk8

For your issue requesting you to check this:

https://youtu.be/cSY-r83pXio

**Comment by xhemp** [comment]
Never had issues before so I know it's configured correctly, there must be something else. I will get on discord later on today to see if we can find out what's going on. Thanks!

**Comment by xhemp** [comment]
My bad on this one, I was being stupid and selected every single time the default 747!
