### ISSUE TITLE
MSFS flight plan not loading.

### ISSUE THREAD

**Issue by KoplaNum** [saltysimulations/salty-747#462]
### Version

v 0.5.1

### Describe the bug

MSFS Flight Plan not loading.

### Expected behaviour

When starting a flight the flight plan from MSFS should be loaded, but even when restarting the flight the flight plan is not loading.

### Steps to reproduce

Select Departure and Arrival airport. 
Select High Enroute Flight plan.
Select salty-747 aircraft. 
Press Fly.

**Comment by ninjomcs** [comment]
using the msfs world map planner is not recommended, use simbrief instead. if you really want to use it you can enable it in salty options > fp sync
