### ISSUE TITLE
Engine 1 and 4 turning off when main tank 1 and 4 are empty

### ISSUE THREAD

**Issue by gimpfenlord** [saltysimulations/salty-747#47]
there seems something broken with the fuel system / crossfeeding.

Main tank 1 and 4 are drained first and once they are empty Engine 1 and 4 shut down and you are not able to start them again.

**Comment by FabioMike06** [comment]
@gimpfenlord  
Do you encounter the same problem even without using the mod?

**Comment by ninjomcs** [comment]
This should be fixed in #49, still unmerged for now.

**Comment by ninjomcs** [comment]
Fixed in #49
