### ISSUE TITLE
Review LNAV and Approach

### ISSUE THREAD

**Issue by GlorySpain** [saltysimulations/salty-747#493]
### Version

 last version

### Describe the bug

when I press the LNAV in principle it works correctly the problem is when it reaches a speed of 260 knots that it begins to force and exceed the indicated speed without that order having been changed and for the approach once the localizer is set the el is not activated automatic altitude descent approximator

### Expected behaviour

press the LNAV and follow the set course without exceeding the indicated airspeed and altitude

### Steps to reproduce

using normal takeoff and landing regulations

### Additional information

It's just to see if you can review it if it's a mistake or my fault, thank you very much

**Comment by Timberolic** [comment]
LNAV has nothing to do with speed management. There is more at play and is most likely the AT not being engaged.

As for this "approximator", what are you referring to? 

We strongly encourage you reach out on our Discord for quicker responses.

**Comment by GlorySpain** [comment]
If I mean that when I activate the LNAV, just like the heading that I set the FMC, sometimes an example of vector type is duplicated:

oak grove
oak grove

something like this and in the approximator the approbach button once the localizer is activated and aligned with the runway the G/S is not activated

It may be my fault but it was in case you could help me or review it in case something similar happens to you, thank you very much for your attention

**Comment by Timberolic** [comment]
I need screenshots of this LNAV "issue" because I have no idea what you are talking about

This G/S has never occurred to me but is a known thing that happens once in awhile. It's either purely cosmetic or you did something wrong.
