### ISSUE TITLE
My game restarts due to invisible crashes or overloads

### ISSUE THREAD

**Issue by GlorySpain** [saltysimulations/salty-747#495]
### Version

Last version

### Describe the bug

Every time I put the engines to maximum it overloads me and it says that the plane has crashed and when I am rolling down the runway the same thing but it says that I have collided with an object

### Expected behaviour

that the described situation is solved

### Steps to reproduce

rolling down the track in singapore happens to me all the time

### Additional information

.

**Comment by Timberolic** [comment]
Crash settings in the sim are not realistic - disable them.

**Comment by GlorySpain** [comment]
ok thank you very much because I didn't know what to do
