### ISSUE TITLE
FMA should display THR REF when TO/GA switch is pressed 

### ISSUE THREAD

**Issue by nobodyn0se** [saltysimulations/salty-747#5]
**Current version**
Default 

**Bug Description** 
When the FDs are on and the A/T is armed, the FMA does not display THR REF when TO/GA button is used for takeoff. 

**Expected Behaviour** 
The FMA must display THR REF which is commanded by the reference limit confirmed in the FMC and shown on the upper EICAS, then go into HOLD mode at 80kts. 

**References** 
https://www.youtube.com/watch?v=6L1vA-xJt-M (thrust application starts at 6:59) 
https://www.youtube.com/watch?v=dPgwzCN8EB0 (goes into HOLD mode at 0:31)

**Comment by ninjomcs** [comment]
Fixed in #9
