### ISSUE TITLE
bug with APP mode and other strange occurances.

### ISSUE THREAD

**Issue by tooldrmr2009** [saltysimulations/salty-747#53]
Was entering ILS for 31L KJFK.  Hit Loc a few miles out of the range, the 747 lined up horizontally with the runway.  I watched the vertical diamond drop for altitude and once it hit the white horizontal line I hit APPR mode.  The PFD switched to LOC, Altitude mode and all 3 autopilot lights came on but right away the APPR light turned off and wouldn't engage. its like altitude mode shut off and wouldn't capture the altitude changes.  I have also noticed when setting VS mode the VS line on the PFD will have the purple box and will climb for a short bit but the VS purple box will go away and it will do what it wants. You have to double click VS again and set it again.  I also had VNAV and LNAV doing some weird stuff and turning randomly when using active pause in MSFS2020.

**Comment by RickBraunn** [comment]
Same issue with APPR mode here

**Comment by thhoppst** [comment]
When you set vs to 0 and then you hit the app knob the plane will follow the gs.

**Comment by dcherrie** [comment]
@tooldrmr2009 I believe these are all FS2020 bugs and not due to the mod. With the recent FS update, the ALT hold when intercepting the G/S bug is now fixed.

**Comment by 747-4EVER** [comment]
Not occurring now as of v0.4.0.
