### ISSUE TITLE
All screen go black.

### ISSUE THREAD

**Issue by krieke58** [saltysimulations/salty-747#57]
During preflight, while entering values in the FMC all screens go black (also frequency  displays and squawk) and it's not possible to turn back on. Occurs on different moments. Not sure what triggers this.

**Comment by ninjomcs** [comment]
Has anyone else experienced this issue?

**Comment by krieke58** [comment]
Removed from Community, started and closed MSFS, put back in Community.
Restarted MSFS . Works !!! :-)
