### ISSUE TITLE
Problem with the flaps and the ap

### ISSUE THREAD

**Issue by val-005** [saltysimulations/salty-747#60]
Hi, 
I recently tested the mod, and I have an old problem with the game that only reappears when the mod is enabled.The plane loses a lot of altitude abnormally once the flaps are removed and when I activate the ap with a set altitude, it stings down.
Sorry if this is not very well explained ^^
The mod has a big potential, thank you for that.

**Comment by BobbyFuzzy** [comment]
The AP is quite aggressive on the 747, I don't think this is an issue with the mod personally, more an Asobo issue. I have experienced this with both the mod installed and not.

When engaging the AP make sure you are close to or following the FD and then the transition should be a little smoother.

**Comment by neshk16** [comment]
Hello val-005, I suggest, engaging the AP modes you plan on using on the ground before takeoff. If you retract flaps when it says on the PFD, you should see little green numbers on the side.  Make sure you fill out the PERF page to the best of your ability as well. If you are using VNAV, verify you have the AP mod installed properly which is included in the Salty Simulations download. Try downloading the latest version 1.10.7. I suggest using Altitude and Speed intervention whilst using VNAV. Make sure you have your cruise altitude properly set in the FMC as well. Hope this helps.
