### ISSUE TITLE
Plane does not move after start

### ISSUE THREAD

**Issue by MCJOJO1** [saltysimulations/salty-747#66]
When I start flight from a parking position and set up all systems the plane does not move. Even 
Neither pushback nor forward. Parking break is released.
Even when I increase thrust it does not show the increase in the panel. 
Do you have an idea?

**Comment by BobbyFuzzy** [comment]
I have never had this issue. Have you tried a different airport/parking spot? Have you experienced this with any other aircraft?

**Comment by saintwolf** [comment]
@MCJOJO1 What are your N1 and N2 readings before you try to add thrust?

**Comment by MCJOJO1** [comment]
Hi guys,

sorry for the delayed response.
Issue is solved. I used the old version for the 747 salty mod. Copied in version 0.1.0 and everything works.

Thanks a lot anyway 👍
