### ISSUE TITLE
RES and STAB not transferring.

### ISSUE THREAD

**Issue by Jonathan-Moore-312** [saltysimulations/salty-747#67]
Have attempted just about everything. I set the force transfer of RES 1 & 4 from AUTO to ON and made sure the STAB tank pump was on, but It is still refusing to transfer to neither the engine nor their respective tanks. Am I missing something?

**Comment by ninjomcs** [comment]
Have you checked out the fuel guide and done everything according to the guide?

**Comment by Jonathan-Moore-312** [comment]
Apologies, I am not seeing a guide other than the README. What guide are you referring to?

**Comment by ninjomcs** [comment]
?fuel in bot-commands in discord

**Comment by Jonathan-Moore-312** [comment]
Looking at it now. I have tried to manually induce the parameters (Combination of Getting the fuel low on start and changing the fuel to a number barely above in the fuel menu). I still have no dice. No EICAS warning either. I am about to do a flight from Washington to Argentina and will not touch the fuel menu on that flight. It is 9 hours but it's better than nothing to test. Will post findings.

This flight will have the following Fuel Readings:
CWT: 113900 LBS
MAIN 1: 18000.97 LBS
MAIN 2: 28000.97 LBS
MAIN 3: 28000.97 LBS
MAIN 4: 18000.97 LBS
RES TANK 1: 10277.79 LBS
RES TANK 4: 10277.79 LBS
STAB TANK: 22110 LBS

This will barely get me there, but I will not touch the fuel menu the entire flight.

**Comment by Jonathan-Moore-312** [comment]
Game Crashed before I finished. STAB did not transfer when it reached the amount indicated in the guide.

**Comment by oscnogbal** [comment]
the STAB tank is supposed to transfer into the CWT during flight but not in once. The aircraft computer transfers fuel from the STAB tank to the CWT as the fuel in the CWT is used. I don't know exactly how the logic works but I could check it up if you are interested in making the aircraft behave that close to reality. Also if the fuel logic is not so clear I could make like a manual explaining how it works. I think that if you know how the system works you understand what you have to do in every situation.
